/**
 * Plan catalog — Sprint 12A (no pricing / payment fields).
 */

import type { FeatureId, PermissionId, PlanDefinition, PlanId } from "./types";

const ALL_FEATURES: FeatureId[] = [
  "dashboard",
  "research",
  "optimization",
  "strategyBuilder",
  "backtesting",
  "paperTrading",
  "exports",
  "aiInsights",
  "watchlists",
  "portfolio",
  "apiKeys",
  "customBranding",
  "prioritySupport",
  "adminConsole",
];

const CORE_PERMS: PermissionId[] = [
  "canEditProfile",
  "canViewSubscription",
  "canManageDevices",
];

export const PLAN_DEFINITIONS: readonly PlanDefinition[] = [
  {
    id: "free",
    name: "Free",
    description: "Core terminal access for individual exploration.",
    sortOrder: 0,
    trialEligible: false,
    features: ["dashboard", "research", "watchlists", "portfolio"],
    permissions: [...CORE_PERMS, "canCreatePortfolio", "canGenerateResearch"],
    limits: {
      storageGb: 1,
      exportsPerMonth: 5,
      researchReportsPerMonth: 10,
      aiRequestsPerMonth: 25,
      portfolioCount: 1,
      watchlists: 2,
      optimizationRunsPerMonth: 0,
      backtestsPerMonth: 0,
      paperTradingAccounts: 0,
      maxDevices: 1,
      maxSeats: 1,
      apiAccess: false,
      prioritySupport: false,
      customBranding: false,
    },
  },
  {
    id: "starter",
    name: "Starter",
    description: "Research + light paper trading for active individuals.",
    sortOrder: 1,
    trialEligible: true,
    features: [
      "dashboard",
      "research",
      "watchlists",
      "portfolio",
      "paperTrading",
      "exports",
      "aiInsights",
    ],
    permissions: [
      ...CORE_PERMS,
      "canCreatePortfolio",
      "canGenerateResearch",
      "canExport",
      "canUsePaperTrading",
      "canUseAiRequests",
    ],
    limits: {
      storageGb: 5,
      exportsPerMonth: 50,
      researchReportsPerMonth: 50,
      aiRequestsPerMonth: 200,
      portfolioCount: 3,
      watchlists: 10,
      optimizationRunsPerMonth: 5,
      backtestsPerMonth: 10,
      paperTradingAccounts: 1,
      maxDevices: 2,
      maxSeats: 1,
      apiAccess: false,
      prioritySupport: false,
      customBranding: false,
    },
  },
  {
    id: "professional",
    name: "Professional",
    description: "Full research lab with optimization and backtesting.",
    sortOrder: 2,
    trialEligible: true,
    features: [
      "dashboard",
      "research",
      "watchlists",
      "portfolio",
      "paperTrading",
      "exports",
      "aiInsights",
      "optimization",
      "strategyBuilder",
      "backtesting",
    ],
    permissions: [
      ...CORE_PERMS,
      "canCreatePortfolio",
      "canGenerateResearch",
      "canExport",
      "canUsePaperTrading",
      "canUseAiRequests",
      "canRunBacktests",
      "canOptimize",
    ],
    limits: {
      storageGb: 25,
      exportsPerMonth: 250,
      researchReportsPerMonth: 250,
      aiRequestsPerMonth: 2000,
      portfolioCount: 10,
      watchlists: 50,
      optimizationRunsPerMonth: 100,
      backtestsPerMonth: 200,
      paperTradingAccounts: 3,
      maxDevices: 3,
      maxSeats: 3,
      apiAccess: false,
      prioritySupport: true,
      customBranding: false,
    },
  },
  {
    id: "institutional",
    name: "Institutional",
    description: "Team seats, API access, and priority research support.",
    sortOrder: 3,
    trialEligible: true,
    features: ALL_FEATURES.filter((f) => f !== "customBranding"),
    permissions: [
      ...CORE_PERMS,
      "canCreatePortfolio",
      "canGenerateResearch",
      "canExport",
      "canUsePaperTrading",
      "canUseAiRequests",
      "canRunBacktests",
      "canOptimize",
      "canAccessApiKeys",
      "canInviteMembers",
      "canManageBilling",
      "canAccessAdmin",
      "canAccessDeveloperMode",
    ],
    limits: {
      storageGb: 100,
      exportsPerMonth: 2000,
      researchReportsPerMonth: 2000,
      aiRequestsPerMonth: 20000,
      portfolioCount: 50,
      watchlists: 200,
      optimizationRunsPerMonth: 1000,
      backtestsPerMonth: 2000,
      paperTradingAccounts: 10,
      maxDevices: 8,
      maxSeats: 25,
      apiAccess: true,
      prioritySupport: true,
      customBranding: false,
    },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Unlimited institutional desk with branding and admin controls.",
    sortOrder: 4,
    trialEligible: false,
    features: [...ALL_FEATURES],
    permissions: [
      ...CORE_PERMS,
      "canCreatePortfolio",
      "canGenerateResearch",
      "canExport",
      "canUsePaperTrading",
      "canUseAiRequests",
      "canRunBacktests",
      "canOptimize",
      "canAccessApiKeys",
      "canInviteMembers",
      "canManageBilling",
      "canAccessAdmin",
      "canAccessDeveloperMode",
    ],
    limits: {
      storageGb: 1000,
      exportsPerMonth: 99999,
      researchReportsPerMonth: 99999,
      aiRequestsPerMonth: 99999,
      portfolioCount: 999,
      watchlists: 999,
      optimizationRunsPerMonth: 99999,
      backtestsPerMonth: 99999,
      paperTradingAccounts: 100,
      maxDevices: 50,
      maxSeats: 500,
      apiAccess: true,
      prioritySupport: true,
      customBranding: true,
    },
  },
] as const;

export function getPlan(id: PlanId): PlanDefinition {
  return PLAN_DEFINITIONS.find((p) => p.id === id) ?? PLAN_DEFINITIONS[0]!;
}

export function planRank(id: PlanId): number {
  return getPlan(id).sortOrder;
}

export function planMeetsMinimum(current: PlanId, required: PlanId): boolean {
  return planRank(current) >= planRank(required);
}
