export {
  SPRINT_10C_FROZEN,
  UI_PLATFORM_STATUS,
  isSprint10CFrozen,
  getDesignSystemStatus,
  getThemeStatus,
  getUILayoutStatus,
  getAccessibilityStatus,
  getPerformanceStatus,
  type DesignSystemStatus,
  type ThemeStatus,
  type UILayoutStatus,
  type AccessibilityStatus,
  type PerformanceStatus,
} from "./platformStatus";
