/**
 * Centralized Strategy Eligibility Matrix (Sprint 11B.2C).
 * Single source of truth for strategy profiles and thresholds.
 * Engine evaluates against this matrix — never embeds strategy rules inline.
 */

import type { MarketRegimeLabel } from "@/src/modules/marketRegime";
import type { StrategyProfile } from "./StrategyEligibilityTypes";

const BULLISH: MarketRegimeLabel[] = ["Strong Bull", "Weak Bull"];
const DIRECTIONAL: MarketRegimeLabel[] = [
  "Strong Bull",
  "Weak Bull",
  "Strong Bear",
  "Weak Bear",
];
const RANGE_FRIENDLY: MarketRegimeLabel[] = ["Sideways", "Low Volatility"];
const VOL_STRESS: MarketRegimeLabel[] = ["High Volatility", "Event Driven"];
const TREND_FOLLOW: MarketRegimeLabel[] = [
  "Strong Bull",
  "Weak Bull",
  "Low Volatility",
];
const BEARISH: MarketRegimeLabel[] = ["Strong Bear", "Weak Bear"];
const ALL_EXCEPT = (
  blocked: MarketRegimeLabel[]
): MarketRegimeLabel[] => {
  const all: MarketRegimeLabel[] = [
    "Strong Bull",
    "Weak Bull",
    "Sideways",
    "Weak Bear",
    "Strong Bear",
    "High Volatility",
    "Low Volatility",
    "Event Driven",
  ];
  const set = new Set(blocked);
  return all.filter((r) => !set.has(r));
};

/**
 * Canonical registered strategy matrix.
 * Priority bands: Scalp 90–80, Intraday 75–65, Swing 60–45, Position 40–30.
 */
export const STRATEGY_MATRIX: readonly StrategyProfile[] = [
  /* ─── Scalp ─── */
  {
    id: "scalping",
    name: "Scalping",
    category: "Scalp",
    supportedRegimes: [
      "Strong Bull",
      "Weak Bull",
      "High Volatility",
      "Event Driven",
      "Sideways",
    ],
    blockedRegimes: ["Strong Bear", "Low Volatility"],
    minimumConfidence: 60,
    minimumMarketStrength: 45,
    minimumBreadth: 40,
    minimumSectorStrength: 40,
    minimumHealthScore: 45,
    priority: 90,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: null,
    minimumVolatilityScore: 35,
  },
  {
    id: "orb",
    name: "ORB",
    category: "Scalp",
    supportedRegimes: [...BULLISH, "Event Driven", "High Volatility"],
    blockedRegimes: ["Strong Bear", "Sideways", "Low Volatility"],
    minimumConfidence: 65,
    minimumMarketStrength: 50,
    minimumBreadth: 45,
    minimumSectorStrength: 45,
    minimumHealthScore: 50,
    priority: 88,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: null,
    minimumVolatilityScore: 30,
  },
  {
    id: "vwap-continuation",
    name: "VWAP Continuation",
    category: "Scalp",
    supportedRegimes: DIRECTIONAL,
    blockedRegimes: ["Sideways", "Low Volatility"],
    minimumConfidence: 65,
    minimumMarketStrength: 52,
    minimumBreadth: 48,
    minimumSectorStrength: 48,
    minimumHealthScore: 50,
    priority: 86,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 75,
    minimumVolatilityScore: null,
  },
  {
    id: "vwap-mean-reversion",
    name: "VWAP Mean Reversion",
    category: "Scalp",
    supportedRegimes: [...RANGE_FRIENDLY, "Weak Bull", "Weak Bear"],
    blockedRegimes: ["Strong Bull", "Strong Bear", "Event Driven"],
    minimumConfidence: 60,
    minimumMarketStrength: 40,
    minimumBreadth: 40,
    minimumSectorStrength: 40,
    minimumHealthScore: 45,
    priority: 84,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: 55,
    minimumVolatilityScore: null,
  },
  {
    id: "liquidity-sweep",
    name: "Liquidity Sweep",
    category: "Scalp",
    supportedRegimes: [...VOL_STRESS, "Weak Bull", "Weak Bear"],
    blockedRegimes: ["Low Volatility", "Strong Bull"],
    minimumConfidence: 55,
    minimumMarketStrength: 40,
    minimumBreadth: 35,
    minimumSectorStrength: 35,
    minimumHealthScore: 40,
    priority: 85,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: null,
    minimumVolatilityScore: 50,
  },
  {
    id: "momentum-continuation",
    name: "Momentum Continuation",
    category: "Scalp",
    supportedRegimes: [...BULLISH, "Event Driven"],
    blockedRegimes: [...BEARISH, "Sideways", "Low Volatility"],
    minimumConfidence: 70,
    minimumMarketStrength: 60,
    minimumBreadth: 55,
    minimumSectorStrength: 55,
    minimumHealthScore: 55,
    priority: 87,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 70,
    minimumVolatilityScore: null,
  },
  {
    id: "opening-range-fade",
    name: "Opening Range Fade",
    category: "Scalp",
    supportedRegimes: [...RANGE_FRIENDLY, "High Volatility", "Weak Bull"],
    blockedRegimes: ["Strong Bull", "Strong Bear", "Event Driven"],
    minimumConfidence: 58,
    minimumMarketStrength: 40,
    minimumBreadth: 40,
    minimumSectorStrength: 40,
    minimumHealthScore: 45,
    priority: 82,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: 70,
    minimumVolatilityScore: null,
  },
  {
    id: "gap-and-go",
    name: "Gap & Go",
    category: "Scalp",
    supportedRegimes: ["Event Driven", "Strong Bull", "High Volatility"],
    blockedRegimes: ["Sideways", "Low Volatility", "Strong Bear"],
    minimumConfidence: 62,
    minimumMarketStrength: 55,
    minimumBreadth: 50,
    minimumSectorStrength: 50,
    minimumHealthScore: 50,
    priority: 89,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: null,
    minimumVolatilityScore: 40,
  },

  /* ─── Intraday ─── */
  {
    id: "relative-strength",
    name: "Relative Strength",
    category: "Intraday",
    supportedRegimes: [...BULLISH, "Low Volatility"],
    blockedRegimes: [...BEARISH, "High Volatility"],
    minimumConfidence: 68,
    minimumMarketStrength: 55,
    minimumBreadth: 52,
    minimumSectorStrength: 58,
    minimumHealthScore: 55,
    priority: 75,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 65,
    minimumVolatilityScore: null,
  },
  {
    id: "institutional-accumulation",
    name: "Institutional Accumulation",
    category: "Intraday",
    supportedRegimes: ["Weak Bull", "Sideways", "Low Volatility"],
    blockedRegimes: ["Strong Bear", "High Volatility", "Event Driven"],
    minimumConfidence: 70,
    minimumMarketStrength: 50,
    minimumBreadth: 48,
    minimumSectorStrength: 52,
    minimumHealthScore: 58,
    priority: 72,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "breakout-retest",
    name: "Breakout Retest",
    category: "Intraday",
    supportedRegimes: [...BULLISH, "Event Driven"],
    blockedRegimes: [...BEARISH, "Sideways"],
    minimumConfidence: 70,
    minimumMarketStrength: 58,
    minimumBreadth: 55,
    minimumSectorStrength: 55,
    minimumHealthScore: 55,
    priority: 74,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 70,
    minimumVolatilityScore: null,
  },
  {
    id: "sector-rotation",
    name: "Sector Rotation",
    category: "Intraday",
    supportedRegimes: [...BULLISH, "Sideways", "Low Volatility"],
    blockedRegimes: ["Strong Bear", "High Volatility"],
    minimumConfidence: 65,
    minimumMarketStrength: 52,
    minimumBreadth: 50,
    minimumSectorStrength: 60,
    minimumHealthScore: 55,
    priority: 73,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 60,
    minimumVolatilityScore: null,
  },
  {
    id: "news-momentum",
    name: "News Momentum",
    category: "Intraday",
    supportedRegimes: [...VOL_STRESS, "Strong Bull", "Weak Bull"],
    blockedRegimes: ["Low Volatility", "Sideways"],
    minimumConfidence: 55,
    minimumMarketStrength: 45,
    minimumBreadth: 40,
    minimumSectorStrength: 40,
    minimumHealthScore: 40,
    priority: 70,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: null,
    minimumVolatilityScore: 45,
  },

  /* ─── Swing ─── */
  {
    id: "vcp",
    name: "VCP",
    category: "Swing",
    supportedRegimes: TREND_FOLLOW,
    blockedRegimes: [...VOL_STRESS, "Strong Bear"],
    minimumConfidence: 72,
    minimumMarketStrength: 58,
    minimumBreadth: 55,
    minimumSectorStrength: 55,
    minimumHealthScore: 60,
    priority: 60,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 45,
    minimumVolatilityScore: null,
  },
  {
    id: "stage-analysis",
    name: "Stage Analysis",
    category: "Swing",
    supportedRegimes: [...BULLISH, "Low Volatility"],
    blockedRegimes: [...VOL_STRESS, "Strong Bear"],
    minimumConfidence: 70,
    minimumMarketStrength: 55,
    minimumBreadth: 52,
    minimumSectorStrength: 52,
    minimumHealthScore: 58,
    priority: 58,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "darvas",
    name: "Darvas",
    category: "Swing",
    supportedRegimes: [...BULLISH],
    blockedRegimes: [...BEARISH, "High Volatility", "Event Driven"],
    minimumConfidence: 70,
    minimumMarketStrength: 58,
    minimumBreadth: 55,
    minimumSectorStrength: 55,
    minimumHealthScore: 58,
    priority: 56,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 55,
    minimumVolatilityScore: null,
  },
  {
    id: "relative-strength-leadership",
    name: "Relative Strength Leadership",
    category: "Swing",
    supportedRegimes: [...BULLISH, "Low Volatility"],
    blockedRegimes: [...BEARISH, "High Volatility"],
    minimumConfidence: 72,
    minimumMarketStrength: 60,
    minimumBreadth: 58,
    minimumSectorStrength: 62,
    minimumHealthScore: 60,
    priority: 59,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "ema-pullback",
    name: "EMA Pullback",
    category: "Swing",
    supportedRegimes: [...BULLISH, "Low Volatility"],
    blockedRegimes: [...BEARISH, "Event Driven"],
    minimumConfidence: 68,
    minimumMarketStrength: 55,
    minimumBreadth: 52,
    minimumSectorStrength: 52,
    minimumHealthScore: 55,
    priority: 57,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 55,
    minimumVolatilityScore: null,
  },
  {
    id: "cup-and-handle",
    name: "Cup & Handle",
    category: "Swing",
    supportedRegimes: [...BULLISH, "Low Volatility"],
    blockedRegimes: [...BEARISH, ...VOL_STRESS],
    minimumConfidence: 72,
    minimumMarketStrength: 58,
    minimumBreadth: 55,
    minimumSectorStrength: 55,
    minimumHealthScore: 60,
    priority: 55,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 45,
    minimumVolatilityScore: null,
  },
  {
    id: "flat-base",
    name: "Flat Base",
    category: "Swing",
    supportedRegimes: ["Weak Bull", "Sideways", "Low Volatility"],
    blockedRegimes: ["Strong Bear", ...VOL_STRESS],
    minimumConfidence: 70,
    minimumMarketStrength: 50,
    minimumBreadth: 50,
    minimumSectorStrength: 52,
    minimumHealthScore: 58,
    priority: 52,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 40,
    minimumVolatilityScore: null,
  },
  {
    id: "fifty-two-week-high",
    name: "52 Week High",
    category: "Swing",
    supportedRegimes: ["Strong Bull", "Weak Bull"],
    blockedRegimes: [...BEARISH, "Sideways", "High Volatility"],
    minimumConfidence: 75,
    minimumMarketStrength: 65,
    minimumBreadth: 60,
    minimumSectorStrength: 60,
    minimumHealthScore: 62,
    priority: 54,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "earnings-momentum",
    name: "Earnings Momentum",
    category: "Swing",
    supportedRegimes: [...BULLISH, "Event Driven"],
    blockedRegimes: ["Strong Bear", "Low Volatility"],
    minimumConfidence: 65,
    minimumMarketStrength: 55,
    minimumBreadth: 50,
    minimumSectorStrength: 55,
    minimumHealthScore: 55,
    priority: 53,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 70,
    minimumVolatilityScore: null,
  },

  /* ─── Position ─── */
  {
    id: "buffett",
    name: "Buffett",
    category: "Position",
    supportedRegimes: ALL_EXCEPT(["High Volatility", "Event Driven", "Strong Bear"]),
    blockedRegimes: ["High Volatility", "Event Driven", "Strong Bear"],
    minimumConfidence: 75,
    minimumMarketStrength: 50,
    minimumBreadth: 45,
    minimumSectorStrength: 45,
    minimumHealthScore: 65,
    priority: 40,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 45,
    minimumVolatilityScore: null,
  },
  {
    id: "graham",
    name: "Graham",
    category: "Position",
    supportedRegimes: ALL_EXCEPT(["High Volatility", "Event Driven"]),
    blockedRegimes: ["High Volatility", "Event Driven"],
    minimumConfidence: 72,
    minimumMarketStrength: 45,
    minimumBreadth: 40,
    minimumSectorStrength: 40,
    minimumHealthScore: 62,
    priority: 38,
    enabled: true,
    blockedRiskModes: [],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "lynch",
    name: "Lynch",
    category: "Position",
    supportedRegimes: [...BULLISH, "Sideways", "Low Volatility"],
    blockedRegimes: ["Strong Bear", "High Volatility", "Event Driven"],
    minimumConfidence: 70,
    minimumMarketStrength: 52,
    minimumBreadth: 48,
    minimumSectorStrength: 50,
    minimumHealthScore: 60,
    priority: 36,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "greenblatt",
    name: "Greenblatt",
    category: "Position",
    supportedRegimes: ALL_EXCEPT(["High Volatility", "Event Driven", "Strong Bear"]),
    blockedRegimes: ["High Volatility", "Event Driven", "Strong Bear"],
    minimumConfidence: 70,
    minimumMarketStrength: 48,
    minimumBreadth: 45,
    minimumSectorStrength: 45,
    minimumHealthScore: 60,
    priority: 34,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 50,
    minimumVolatilityScore: null,
  },
  {
    id: "quality-compounder",
    name: "Quality Compounder",
    category: "Position",
    supportedRegimes: [...BULLISH, "Sideways", "Low Volatility"],
    blockedRegimes: ["Strong Bear", "High Volatility", "Event Driven"],
    minimumConfidence: 78,
    minimumMarketStrength: 55,
    minimumBreadth: 50,
    minimumSectorStrength: 52,
    minimumHealthScore: 68,
    priority: 42,
    enabled: true,
    blockedRiskModes: ["Risk Off"],
    maximumVolatilityScore: 45,
    minimumVolatilityScore: null,
  },
] as const;

/**
 * Lookup a strategy profile by id from the canonical matrix.
 */
export function getStrategyProfile(
  strategyId: string,
  matrix: readonly StrategyProfile[] = STRATEGY_MATRIX
): StrategyProfile | undefined {
  return matrix.find((profile) => profile.id === strategyId);
}

/**
 * Return enabled profiles only (still subject to eligibility gates).
 */
export function getEnabledStrategyProfiles(
  matrix: readonly StrategyProfile[] = STRATEGY_MATRIX
): StrategyProfile[] {
  return matrix.filter((profile) => profile.enabled);
}

/**
 * Clone matrix with optional per-strategy overrides (tests / config).
 */
export function resolveStrategyMatrix(
  overrides?: readonly Partial<StrategyProfile>[]
): StrategyProfile[] {
  if (!overrides || overrides.length === 0) {
    return STRATEGY_MATRIX.map((p) => ({ ...p }));
  }

  const byId = new Map(overrides.map((o) => [o.id, o]));
  return STRATEGY_MATRIX.map((profile) => {
    const override = byId.get(profile.id);
    if (!override) return { ...profile };
    return {
      ...profile,
      ...override,
      supportedRegimes: override.supportedRegimes ?? [...profile.supportedRegimes],
      blockedRegimes: override.blockedRegimes ?? [...profile.blockedRegimes],
      blockedRiskModes: override.blockedRiskModes ?? [...profile.blockedRiskModes],
    };
  });
}
