/**
 * AI output quality guardrails — attribution, confidence, financial consistency.
 */

import type { CompanyContext } from "@/lib/ai/context/companyContext";
import type { RetrievedChunk } from "@/lib/rag/retriever";
import { getPlatformEnv } from "@/lib/platform/env";

export interface QualityCheckResult {
  passed: boolean;
  confidenceScore: number;
  warnings: string[];
  requiresAttribution: boolean;
}

export interface FinancialConsistencyInput {
  context: CompanyContext | null;
  generatedText: string;
}

function extractNumbers(text: string): number[] {
  const matches = text.match(/-?\d+(?:\.\d+)?/g) ?? [];
  return matches.map(Number).filter((n) => Number.isFinite(n));
}

export function evaluateOutputQuality(input: {
  answer: string;
  ragChunks: RetrievedChunk[];
  confidenceScore?: number;
}): QualityCheckResult {
  const warnings: string[] = [];
  const threshold = getPlatformEnv().AI_CONFIDENCE_THRESHOLD;
  const confidenceScore = input.confidenceScore ?? 60;
  const requiresAttribution = input.ragChunks.length > 0;

  if (requiresAttribution) {
    const hasCitation =
      /\[source:|\(source:|annual report|quarterly report|concall|filing|page \d+/i.test(
        input.answer
      );
    if (!hasCitation) {
      warnings.push(
        "RAG context was available but the answer lacks explicit source attribution."
      );
    }
  }

  const speculativePatterns = [
    /guaranteed\s+returns?/i,
    /will\s+definitely/i,
    /100%\s+certain/i,
    /insider\s+information/i,
  ];
  for (const pattern of speculativePatterns) {
    if (pattern.test(input.answer)) {
      warnings.push(`Potentially speculative language detected: ${pattern.source}`);
    }
  }

  if (confidenceScore < threshold) {
    warnings.push(
      `Confidence ${confidenceScore} is below institutional threshold ${threshold}.`
    );
  }

  return {
    passed: warnings.length === 0,
    confidenceScore,
    warnings,
    requiresAttribution,
  };
}

export function validateFinancialConsistency(
  input: FinancialConsistencyInput
): string[] {
  const issues: string[] = [];
  const fi = input.context?.financialIntelligence;
  if (!fi) return issues;

  const text = input.generatedText.toLowerCase();
  const pe = fi.ratios.pe;
  const roe = fi.ratios.roe;

  if (pe != null && Number.isFinite(pe)) {
    const peMentions = extractNumbers(input.generatedText).filter(
      (n) => Math.abs(n - pe) <= 2 || Math.abs(n - pe) / pe > 0.35
    );
    if (/p\/e|pe ratio|price-to-earnings/i.test(text) && peMentions.length === 0) {
      issues.push(
        `Generated text discusses P/E but does not align with computed P/E (${pe.toFixed(1)}x).`
      );
    }
  }

  if (roe != null && Number.isFinite(roe)) {
    if (/roe|return on equity/i.test(text) && !input.generatedText.includes(roe.toFixed(1))) {
      const roeInText = extractNumbers(input.generatedText).some(
        (n) => Math.abs(n - roe) <= 1.5
      );
      if (!roeInText) {
        issues.push(
          `Generated text discusses ROE but may not match computed ROE (${roe.toFixed(1)}%).`
        );
      }
    }
  }

  return issues;
}

export function appendQualityDisclaimer(warnings: string[]): string {
  if (warnings.length === 0) return "";
  return [
    "",
    "---",
    "**Quality Notice:**",
    ...warnings.map((warning) => `- ${warning}`),
    "",
    "_This notice is generated by EquityOS quality guardrails. Verify figures against live fundamentals._",
  ].join("\n");
}

export const RAG_ATTRIBUTION_DIRECTIVE = `When institutional RAG chunks are provided, you MUST cite sources inline.
Format citations as: [Source: {document type}, {year/quarter}, p.{page}].
Never quote filings that are not present in the supplied RAG context.`;

export const HALLUCINATION_DIRECTIVE = `Never fabricate financial figures, filings, management quotes, or price targets.
If data is unavailable in supplied context, explicitly state "data unavailable" rather than estimating.`;
