/**
 * Built-in editable strategy templates (Sprint 11D).
 */

import type { StrategyBuildingBlocks, StrategyRules, StrategyTemplate } from "./types";

function blocks(
  partial: Partial<StrategyBuildingBlocks> &
    Pick<StrategyBuildingBlocks, "universe" | "marketRegime" | "positionSizing" | "holdingPeriod">
): StrategyBuildingBlocks {
  return {
    technicalIndicators: partial.technicalIndicators ?? [],
    fundamentalFilters: partial.fundamentalFilters ?? [],
    valuationFilters: partial.valuationFilters ?? [],
    volumeFilters: partial.volumeFilters ?? [],
    momentumFilters: partial.momentumFilters ?? [],
    riskRules: partial.riskRules ?? ["Max risk 1% per trade"],
    exitRules: partial.exitRules ?? ["Target or stop"],
    positionSizing: partial.positionSizing,
    holdingPeriod: partial.holdingPeriod,
    universe: partial.universe,
    marketRegime: partial.marketRegime,
  };
}

function rules(partial: Partial<StrategyRules>): StrategyRules {
  return {
    entry: partial.entry ?? [],
    exit: partial.exit ?? [],
    stopLossPct: partial.stopLossPct ?? 4,
    targetPct: partial.targetPct ?? 8,
    trailingStopPct: partial.trailingStopPct ?? null,
    positionSizePct: partial.positionSizePct ?? 5,
    holdingMinDays: partial.holdingMinDays ?? 3,
    holdingMaxDays: partial.holdingMaxDays ?? 20,
    riskRules: partial.riskRules ?? ["Risk ≤ 1% equity per idea"],
    marketFilters: partial.marketFilters ?? [],
    sectorFilters: partial.sectorFilters ?? [],
    liquidityFilters: partial.liquidityFilters ?? ["ADV ≥ ₹5 Cr"],
  };
}

export const STRATEGY_TEMPLATES: readonly StrategyTemplate[] = [
  {
    id: "swing-breakout",
    name: "Swing Breakout",
    description: "Multi-day breakouts with volume confirmation and trailing risk.",
    category: "Trend",
    tags: ["swing", "breakout", "trend"],
    blocks: blocks({
      technicalIndicators: ["20/50 EMA", "Donchian 20", "ATR(14)"],
      volumeFilters: ["Relative volume ≥ 1.5×"],
      momentumFilters: ["Price above 50 EMA"],
      riskRules: ["ATR stop 1.5×", "Max risk 1%"],
      exitRules: ["Trail 2× ATR", "Time stop 15 days"],
      positionSizing: "Volatility-scaled 1% risk",
      holdingPeriod: "5–15 trading days",
      universe: "Nifty 500",
      marketRegime: "Bull",
    }),
    rules: rules({
      entry: ["Close breaks 20-day high", "Volume ≥ 1.5× 20-day AVG"],
      exit: ["Trail stop hit", "Close below 10 EMA"],
      stopLossPct: 3.5,
      targetPct: 9,
      trailingStopPct: 4,
      positionSizePct: 4,
      holdingMinDays: 5,
      holdingMaxDays: 15,
      marketFilters: ["Index above 50 DMA"],
      sectorFilters: ["Exclude utilities"],
    }),
  },
  {
    id: "momentum",
    name: "Momentum",
    description: "Relative strength rotation into sustained directional leaders.",
    category: "Momentum",
    tags: ["momentum", "rs", "rotation"],
    blocks: blocks({
      technicalIndicators: ["RSI(14)", "MACD", "52-week high proximity"],
      momentumFilters: ["6-month RS rank top quartile"],
      volumeFilters: ["ADV ≥ ₹10 Cr"],
      fundamentalFilters: ["EPS growth > 10%"],
      positionSizing: "Equal weight 5 slots",
      holdingPeriod: "20–60 trading days",
      universe: "Nifty 500",
      marketRegime: "Bull",
    }),
    rules: rules({
      entry: ["RS rank ≥ 75", "Price > 50 & 200 EMA"],
      exit: ["RS rank < 50", "MACD bearish cross"],
      stopLossPct: 8,
      targetPct: 18,
      trailingStopPct: 10,
      positionSizePct: 8,
      holdingMinDays: 20,
      holdingMaxDays: 60,
    }),
  },
  {
    id: "mean-reversion",
    name: "Mean Reversion",
    description: "Fade stretched moves toward VWAP/mean with tight stops.",
    category: "Mean Reversion",
    tags: ["mean-reversion", "rsi", "fade"],
    blocks: blocks({
      technicalIndicators: ["RSI(2)", "Bollinger 20", "VWAP"],
      volumeFilters: ["Climax volume day"],
      riskRules: ["Hard stop 2%", "Max 2 concurrent"],
      exitRules: ["Mean touch", "Time stop 5 days"],
      positionSizing: "Fixed fractional 0.75% risk",
      holdingPeriod: "1–5 trading days",
      universe: "Liquid Universe",
      marketRegime: "Sideways",
    }),
    rules: rules({
      entry: ["RSI(2) < 10", "Close below lower band"],
      exit: ["Close back to mid-band", "RSI(2) > 70"],
      stopLossPct: 2.5,
      targetPct: 4,
      trailingStopPct: null,
      positionSizePct: 3,
      holdingMinDays: 1,
      holdingMaxDays: 5,
      marketFilters: ["Avoid gap days > 3%"],
    }),
  },
  {
    id: "trend-following",
    name: "Trend Following",
    description: "Systematic trend capture with dual moving averages and ATR risk.",
    category: "Trend",
    tags: ["trend", "ma", "atr"],
    blocks: blocks({
      technicalIndicators: ["50/200 EMA", "ADX(14)", "ATR(14)"],
      momentumFilters: ["ADX ≥ 20"],
      riskRules: ["Chandelier exit 3× ATR"],
      exitRules: ["MA cross exit"],
      positionSizing: "Risk parity 1%",
      holdingPeriod: "30–120 trading days",
      universe: "Nifty 500",
      marketRegime: "Any",
    }),
    rules: rules({
      entry: ["50 EMA > 200 EMA", "ADX ≥ 20"],
      exit: ["50 EMA < 200 EMA"],
      stopLossPct: 10,
      targetPct: 25,
      trailingStopPct: 12,
      positionSizePct: 6,
      holdingMinDays: 30,
      holdingMaxDays: 120,
    }),
  },
  {
    id: "growth-investing",
    name: "Growth Investing",
    description: "Quality growth screen with earnings momentum and drawdown caps.",
    category: "Growth",
    tags: ["growth", "fundamental", "quality"],
    blocks: blocks({
      fundamentalFilters: ["Revenue CAGR ≥ 15%", "ROE ≥ 15%"],
      valuationFilters: ["PEG ≤ 1.5"],
      momentumFilters: ["Price above 100 DMA"],
      riskRules: ["Portfolio DD cap 12%"],
      positionSizing: "Conviction-weighted max 8%",
      holdingPeriod: "90–250 trading days",
      universe: "Nifty 500",
      marketRegime: "Bull",
    }),
    rules: rules({
      entry: ["EPS surprise positive 2 quarters", "PEG ≤ 1.5"],
      exit: ["Growth deceleration", "Breach of thesis stop"],
      stopLossPct: 15,
      targetPct: 40,
      trailingStopPct: 18,
      positionSizePct: 7,
      holdingMinDays: 90,
      holdingMaxDays: 250,
      sectorFilters: ["Prefer tech / consumer"],
    }),
  },
  {
    id: "value-investing",
    name: "Value Investing",
    description: "Systematic value with quality filters and multi-quarter holding.",
    category: "Value",
    tags: ["value", "pe", "quality"],
    blocks: blocks({
      valuationFilters: ["P/E < sector median", "P/B < 2"],
      fundamentalFilters: ["Debt/Equity < 1", "Positive FCF"],
      riskRules: ["Max sector weight 25%"],
      positionSizing: "Equal weight 10 slots",
      holdingPeriod: "120–365 days",
      universe: "Nifty 500",
      marketRegime: "Any",
    }),
    rules: rules({
      entry: ["P/E discount ≥ 20% vs sector", "FCF yield ≥ 4%"],
      exit: ["Valuation mean reversion", "Quality break"],
      stopLossPct: 18,
      targetPct: 35,
      trailingStopPct: null,
      positionSizePct: 10,
      holdingMinDays: 120,
      holdingMaxDays: 365,
    }),
  },
  {
    id: "dividend",
    name: "Dividend",
    description: "Income rotation across stable dividend payers with DD caps.",
    category: "Income",
    tags: ["dividend", "income", "defensive"],
    blocks: blocks({
      fundamentalFilters: ["Dividend yield ≥ 2.5%", "Payout stable 5y"],
      valuationFilters: ["Yield not top 5% trap"],
      riskRules: ["Max DD 10%"],
      positionSizing: "Equal weight income sleeve",
      holdingPeriod: "180–365 days",
      universe: "Nifty 50",
      marketRegime: "Any",
    }),
    rules: rules({
      entry: ["Yield ≥ 2.5%", "Payout < 70%"],
      exit: ["Dividend cut", "Yield compression"],
      stopLossPct: 12,
      targetPct: 20,
      trailingStopPct: null,
      positionSizePct: 8,
      holdingMinDays: 180,
      holdingMaxDays: 365,
      sectorFilters: ["Prefer financials / consumer staples"],
    }),
  },
  {
    id: "quality",
    name: "Quality",
    description: "High-ROE compounders with low leverage and trend confirmation.",
    category: "Quality",
    tags: ["quality", "roe", "compounders"],
    blocks: blocks({
      fundamentalFilters: ["ROE ≥ 18%", "Gross margin stable"],
      valuationFilters: ["Quality premium acceptable"],
      technicalIndicators: ["Price > 200 DMA"],
      positionSizing: "Barbell core 6–8%",
      holdingPeriod: "120–300 days",
      universe: "Nifty 500",
      marketRegime: "Bull",
    }),
    rules: rules({
      entry: ["ROE ≥ 18%", "Price > 200 DMA"],
      exit: ["ROE < 12%", "Close < 200 DMA"],
      stopLossPct: 14,
      targetPct: 30,
      trailingStopPct: 16,
      positionSizePct: 7,
      holdingMinDays: 120,
      holdingMaxDays: 300,
    }),
  },
  {
    id: "small-cap-momentum",
    name: "Small Cap Momentum",
    description: "Liquidity-gated small-cap momentum with tighter risk controls.",
    category: "Momentum",
    tags: ["smallcap", "momentum", "liquidity"],
    blocks: blocks({
      momentumFilters: ["3-month RS top decile"],
      volumeFilters: ["ADV ≥ ₹3 Cr", "Spread ≤ 0.5%"],
      riskRules: ["Max position 3%", "Hard liquidity gate"],
      positionSizing: "Liquidity-capped 0.8% risk",
      holdingPeriod: "10–40 days",
      universe: "Smallcap 250",
      marketRegime: "Bull",
    }),
    rules: rules({
      entry: ["RS top 10%", "ADV ≥ ₹3 Cr"],
      exit: ["RS drop out of top 30%", "Liquidity breach"],
      stopLossPct: 7,
      targetPct: 16,
      trailingStopPct: 8,
      positionSizePct: 3,
      holdingMinDays: 10,
      holdingMaxDays: 40,
      liquidityFilters: ["ADV ≥ ₹3 Cr", "Spread ≤ 0.5%"],
      marketFilters: ["Avoid high-vol regime"],
    }),
  },
  {
    id: "low-volatility",
    name: "Low Volatility",
    description: "Defensive low-beta sleeve with drawdown and volatility caps.",
    category: "Defensive",
    tags: ["low-vol", "defensive", "beta"],
    blocks: blocks({
      technicalIndicators: ["60-day realized vol"],
      fundamentalFilters: ["Beta ≤ 0.8"],
      riskRules: ["Vol target 10%", "DD cap 8%"],
      positionSizing: "Inverse-vol weights",
      holdingPeriod: "60–180 days",
      universe: "Nifty 50",
      marketRegime: "Any",
    }),
    rules: rules({
      entry: ["Beta ≤ 0.8", "Realized vol bottom quartile"],
      exit: ["Vol spike above median", "Beta > 1.0"],
      stopLossPct: 8,
      targetPct: 14,
      trailingStopPct: 9,
      positionSizePct: 9,
      holdingMinDays: 60,
      holdingMaxDays: 180,
      marketFilters: ["Prefer calm / sideways regimes"],
    }),
  },
] as const;

export function getTemplateById(id: string | null | undefined): StrategyTemplate | null {
  if (!id) return null;
  return STRATEGY_TEMPLATES.find((t) => t.id === id) ?? null;
}

export function cloneTemplate(template: StrategyTemplate): StrategyTemplate {
  return {
    ...template,
    tags: [...template.tags],
    blocks: {
      ...template.blocks,
      technicalIndicators: [...template.blocks.technicalIndicators],
      fundamentalFilters: [...template.blocks.fundamentalFilters],
      valuationFilters: [...template.blocks.valuationFilters],
      volumeFilters: [...template.blocks.volumeFilters],
      momentumFilters: [...template.blocks.momentumFilters],
      riskRules: [...template.blocks.riskRules],
      exitRules: [...template.blocks.exitRules],
    },
    rules: {
      ...template.rules,
      entry: [...template.rules.entry],
      exit: [...template.rules.exit],
      riskRules: [...template.rules.riskRules],
      marketFilters: [...template.rules.marketFilters],
      sectorFilters: [...template.rules.sectorFilters],
      liquidityFilters: [...template.rules.liquidityFilters],
    },
  };
}
