/**
 * Strategy Framework public exports — Sprint 11B.3A.
 */

export type {
  StrategyAnalysisResult,
  StrategyCategory,
  StrategyEngineOptions,
  StrategyEngineResult,
  StrategyExecutionContext,
  StrategyId,
  StrategyLifecycleSnapshot,
  StrategyLifecycleState,
  StrategyMarketInput,
  StrategyRegistration,
  StrategySignal,
  StrategySignalType,
  StrategyTargets,
  StrategyValidationIssue,
  StrategyValidationResult,
} from "./StrategyTypes";

export type { StrategyFrameworkConfig } from "./StrategyConstants";

export {
  DEFAULT_STRATEGY_FRAMEWORK_CONFIG,
  STRATEGY_CATEGORIES,
  STRATEGY_LIFECYCLE_STATES,
  STRATEGY_LIFECYCLE_TRANSITIONS,
  STRATEGY_SIGNAL_TYPES,
} from "./StrategyConstants";

export { BaseStrategy } from "./BaseStrategy";
export { StrategyLifecycle } from "./StrategyLifecycle";
export {
  StrategyRegistry,
  getStrategyRegistry,
  resetStrategyRegistry,
} from "./StrategyRegistry";
export {
  StrategyFactory,
  getStrategyFactory,
  resetStrategyFactory,
} from "./StrategyFactory";
export {
  StrategyValidator,
  createDefaultStrategyValidator,
} from "./StrategyValidator";
export {
  StrategyEngine,
  getStrategyEngine,
  resetStrategyEngine,
} from "./StrategyEngine";

export {
  buildStrategySignal,
  calculateRiskRewardRatio,
  clampScore,
  createIgnoreSignal,
  defaultHoldingPeriod,
  emptyValidationResult,
  isFinitePositivePrice,
  isStrategyEligible,
  isValidMarketInput,
  mergeValidationResults,
  resolveStrategyFrameworkConfig,
} from "./StrategyUtils";

export {
  ORBStrategy,
  ORBDetector,
  ORBValidator,
  ORBTradeBuilder,
  calculateOpeningRange,
  calculateORBConfidence,
  calculateORBEntry,
  calculateORBTradeQuality,
  calculateORBConviction,
  classifyORBSignalGrade,
  createORBStrategyRegistration,
  detectBreakout,
  detectORB,
  ensureORBRegistered,
  executeORBThroughEngine,
  executeORBWithPipeline,
  generateORBTargets,
  getORBDetector,
  getORBMetrics,
  getORBTradeBuilder,
  registerORBStrategy,
  resetORBDetector,
  resetORBMetrics,
  resetORBTradeBuilder,
  resolveStopLoss,
  validateBreadth,
  validateLiquidity,
  validateMarket,
  validateVolume,
  DEFAULT_ORB_CONFIG,
  DEFAULT_ORB_TRADE_CONFIG,
  ORB_STRATEGY_ID,
  type ORBCandle,
  type ORBConfig,
  type ORBDetection,
  type ORBDetectionContext,
  type ORBDirection,
  type ORBExplainability,
  type ORBInstitutionalScore,
  type ORBMarketData,
  type ORBMetricsSnapshot,
  type ORBStrategyInput,
  type ORBTradeConfig,
  type ORBTradeSetup,
  type ORBQualityGrade,
  type ORBSignalGrade,
} from "./orb";

export {
  VWAPContinuationStrategy,
  VWAPContinuationDetector,
  VWAPContinuationValidator,
  VWAPContinuationTradeBuilder,
  buildVWAPContinuationExplainability,
  buildVWAPContinuationInstitutionalScore,
  buildVWAPContinuationSummary,
  calculateConfidence as calculateVWAPContinuationConfidence,
  calculateVWAPContinuationConviction,
  calculateVWAPContinuationEntry,
  calculateVWAPContinuationSignalGrade,
  calculateVWAPContinuationTradeQuality,
  calculateVWAPSlope,
  classifyVWAPContinuationSignalGrade,
  createVWAPContinuationStrategyRegistration,
  detectBounce,
  detectPullback,
  detectVWAPContinuation,
  ensureVWAPContinuationRegistered,
  executeVWAPContinuationThroughEngine,
  executeVWAPContinuationWithPipeline,
  generateVWAPContinuationTargets,
  getVWAPContinuationDetector,
  getVWAPContinuationMetrics,
  getVWAPContinuationTradeBuilder,
  measureVWAPDistance,
  registerVWAPContinuationStrategy,
  resetVWAPContinuationDetector,
  resetVWAPContinuationMetrics,
  resetVWAPContinuationTradeBuilder,
  resolveStopLoss as resolveVWAPContinuationStopLoss,
  validateBreadth as validateVWAPContinuationBreadth,
  validateMarket as validateVWAPContinuationMarket,
  validateSector as validateVWAPContinuationSector,
  validateTrend,
  validateVolume as validateVWAPContinuationVolume,
  DEFAULT_VWAP_CONTINUATION_CONFIG,
  DEFAULT_VWAP_CONTINUATION_TRADE_CONFIG,
  VWAP_CONTINUATION_STRATEGY_ID,
  type VWAPCandle,
  type VWAPContinuationConfig,
  type VWAPContinuationDetection,
  type VWAPContinuationDetectionContext,
  type VWAPContinuationDirection,
  type VWAPContinuationExplainability,
  type VWAPContinuationInstitutionalScore,
  type VWAPContinuationMarketData,
  type VWAPContinuationMetricsSnapshot,
  type VWAPContinuationStrategyInput,
  type VWAPContinuationTradeConfig,
  type VWAPContinuationTradeSetup,
  type VWAPContinuationQualityGrade,
  type VWAPContinuationSignalGrade,
} from "./vwapContinuation";

export {
  VWAPMeanReversionStrategy,
  VWAPMeanReversionDetector,
  VWAPMeanReversionValidator,
  VWAPMeanReversionTradeBuilder,
  buildVWAPMeanReversionExplainability,
  buildVWAPMeanReversionInstitutionalScore,
  buildVWAPMeanReversionSummary,
  calculateConfidence as calculateVWAPMeanReversionConfidence,
  calculateDeviation,
  calculateVWAPBands,
  calculateVWAPMeanReversionConviction,
  calculateVWAPMeanReversionEntry,
  calculateVWAPMeanReversionSignalGrade,
  calculateVWAPMeanReversionTradeQuality,
  createVWAPMeanReversionStrategyRegistration,
  detectExhaustion,
  detectReversal,
  detectVWAPMeanReversion,
  ensureVWAPMeanReversionRegistered,
  executeVWAPMeanReversionThroughEngine,
  executeVWAPMeanReversionWithPipeline,
  generateVWAPMeanReversionTargets,
  getVWAPMeanReversionDetector,
  getVWAPMeanReversionMetrics,
  getVWAPMeanReversionTradeBuilder,
  registerVWAPMeanReversionStrategy,
  resetVWAPMeanReversionDetector,
  resetVWAPMeanReversionMetrics,
  resetVWAPMeanReversionTradeBuilder,
  resolveStopLoss as resolveVWAPMeanReversionStopLoss,
  validateBreadth as validateVWAPMeanReversionBreadth,
  validateRSI,
  validateSector as validateVWAPMeanReversionSector,
  validateVolume as validateVWAPMeanReversionVolume,
  DEFAULT_VWAP_MEAN_REVERSION_CONFIG,
  DEFAULT_VWAP_MEAN_REVERSION_TRADE_CONFIG,
  VWAP_MEAN_REVERSION_STRATEGY_ID,
  type VWAPMeanReversionCandle,
  type VWAPMeanReversionConfig,
  type VWAPMeanReversionDetection,
  type VWAPMeanReversionDetectionContext,
  type VWAPMeanReversionDirection,
  type VWAPMeanReversionExplainability,
  type VWAPMeanReversionInstitutionalScore,
  type VWAPMeanReversionMarketData,
  type VWAPMeanReversionMetricsSnapshot,
  type VWAPMeanReversionStrategyInput,
  type VWAPMeanReversionTradeConfig,
  type VWAPMeanReversionTradeSetup,
  type VWAPMeanReversionQualityGrade,
  type VWAPMeanReversionSignalGrade,
  type VWAPStandardDeviationBands,
} from "./vwapMeanReversion";

export {
  LiquiditySweepStrategy,
  LiquiditySweepDetector,
  LiquiditySweepValidator,
  LiquiditySweepTradeBuilder,
  buildLiquiditySweepExplainability,
  buildLiquiditySweepInstitutionalScore,
  buildLiquiditySweepSummary,
  calculateConfidence as calculateLiquiditySweepConfidence,
  calculateLiquiditySweepConviction,
  calculateLiquiditySweepEntry,
  calculateLiquiditySweepSignalGrade,
  calculateLiquiditySweepTradeQuality,
  createLiquiditySweepStrategyRegistration,
  detectLiquiditySweep,
  detectReversalCandle,
  ensureLiquiditySweepRegistered,
  executeLiquiditySweepThroughEngine,
  executeLiquiditySweepWithPipeline,
  generateLiquiditySweepTargets,
  getLiquiditySweepDetector,
  getLiquiditySweepMetrics,
  getLiquiditySweepTradeBuilder,
  registerLiquiditySweepStrategy,
  resetLiquiditySweepDetector,
  resetLiquiditySweepMetrics,
  resetLiquiditySweepTradeBuilder,
  resolveStopLoss as resolveLiquiditySweepStopLoss,
  validateBreadth as validateLiquiditySweepBreadth,
  validateSector as validateLiquiditySweepSector,
  validateVolume as validateLiquiditySweepVolume,
  DEFAULT_LIQUIDITY_SWEEP_CONFIG,
  DEFAULT_LIQUIDITY_SWEEP_TRADE_CONFIG,
  LIQUIDITY_SWEEP_STRATEGY_ID,
  type LiquiditySweepCandle,
  type LiquiditySweepConfig,
  type LiquiditySweepDetection,
  type LiquiditySweepDetectionContext,
  type LiquiditySweepDirection,
  type LiquiditySweepExplainability,
  type LiquiditySweepInstitutionalScore,
  type LiquiditySweepMarketData,
  type LiquiditySweepMetricsSnapshot,
  type LiquiditySweepStrategyInput,
  type LiquiditySweepTradeConfig,
  type LiquiditySweepTradeSetup,
  type LiquiditySweepQualityGrade,
  type LiquiditySweepSignalGrade,
  type LiquiditySweepType,
} from "./liquiditySweep";

export {
  MomentumContinuationStrategy,
  MomentumContinuationDetector,
  MomentumContinuationValidator,
  MomentumContinuationTradeBuilder,
  buildMomentumContinuationExplainability,
  buildMomentumContinuationInstitutionalScore,
  buildMomentumContinuationSummary,
  calculateConfidence as calculateMomentumContinuationConfidence,
  calculateMomentumContinuationConviction,
  calculateMomentumContinuationEntry,
  calculateMomentumContinuationSignalGrade,
  calculateMomentumContinuationTradeQuality,
  createMomentumContinuationStrategyRegistration,
  detectMomentumContinuation,
  detectTrendStructure,
  ensureMomentumContinuationRegistered,
  executeMomentumContinuationThroughEngine,
  executeMomentumContinuationWithPipeline,
  generateMomentumContinuationTargets,
  getMomentumContinuationDetector,
  getMomentumContinuationMetrics,
  getMomentumContinuationTradeBuilder,
  registerMomentumContinuationStrategy,
  resetMomentumContinuationDetector,
  resetMomentumContinuationMetrics,
  resetMomentumContinuationTradeBuilder,
  resolveStopLoss as resolveMomentumContinuationStopLoss,
  validateAdx as validateMomentumContinuationAdx,
  validateBreadth as validateMomentumContinuationBreadth,
  validateSector as validateMomentumContinuationSector,
  validateVolume as validateMomentumContinuationVolume,
  DEFAULT_MOMENTUM_CONTINUATION_CONFIG,
  DEFAULT_MOMENTUM_CONTINUATION_TRADE_CONFIG,
  MOMENTUM_CONTINUATION_STRATEGY_ID,
  type MomentumContinuationCandle,
  type MomentumContinuationConfig,
  type MomentumContinuationDetection,
  type MomentumContinuationDetectionContext,
  type MomentumContinuationDirection,
  type MomentumContinuationExplainability,
  type MomentumContinuationInstitutionalScore,
  type MomentumContinuationMarketData,
  type MomentumContinuationMetricsSnapshot,
  type MomentumContinuationStrategyInput,
  type MomentumContinuationTradeConfig,
  type MomentumContinuationTradeSetup,
  type MomentumContinuationQualityGrade,
  type MomentumContinuationSignalGrade,
} from "./momentumContinuation";

export {
  RelativeStrengthIntradayStrategy,
  RelativeStrengthIntradayDetector,
  RelativeStrengthIntradayValidator,
  RelativeStrengthIntradayTradeBuilder,
  buildRelativeStrengthIntradayExplainability,
  buildRelativeStrengthIntradayInstitutionalScore,
  buildRelativeStrengthIntradaySummary,
  calculateConfidence as calculateRelativeStrengthIntradayConfidence,
  calculateRelativeStrengthIntradayConviction,
  calculateRelativeStrengthIntradayEntry,
  calculateRelativeStrengthIntradaySignalGrade,
  calculateRelativeStrengthIntradayTradeQuality,
  createRelativeStrengthIntradayStrategyRegistration,
  detectRelativeStrengthIntraday,
  detectTrendStructure as detectRelativeStrengthIntradayTrendStructure,
  ensureRelativeStrengthIntradayRegistered,
  evaluateRelativeStrengthLeadership,
  executeRelativeStrengthIntradayThroughEngine,
  executeRelativeStrengthIntradayWithPipeline,
  generateRelativeStrengthIntradayTargets,
  getRelativeStrengthIntradayDetector,
  getRelativeStrengthIntradayMetrics,
  getRelativeStrengthIntradayTradeBuilder,
  registerRelativeStrengthIntradayStrategy,
  resetRelativeStrengthIntradayDetector,
  resetRelativeStrengthIntradayMetrics,
  resetRelativeStrengthIntradayTradeBuilder,
  resolveStopLoss as resolveRelativeStrengthIntradayStopLoss,
  validateBreadth as validateRelativeStrengthIntradayBreadth,
  validateSector as validateRelativeStrengthIntradaySector,
  validateVolume as validateRelativeStrengthIntradayVolume,
  DEFAULT_RELATIVE_STRENGTH_INTRADAY_CONFIG,
  DEFAULT_RELATIVE_STRENGTH_INTRADAY_TRADE_CONFIG,
  RELATIVE_STRENGTH_INTRADAY_STRATEGY_ID,
  type RelativeStrengthIntradayCandle,
  type RelativeStrengthIntradayConfig,
  type RelativeStrengthIntradayDetection,
  type RelativeStrengthIntradayDetectionContext,
  type RelativeStrengthIntradayDirection,
  type RelativeStrengthIntradayExplainability,
  type RelativeStrengthIntradayInstitutionalScore,
  type RelativeStrengthIntradayMarketData,
  type RelativeStrengthIntradayMetricsSnapshot,
  type RelativeStrengthIntradayStrategyInput,
  type RelativeStrengthIntradayTradeConfig,
  type RelativeStrengthIntradayTradeSetup,
  type RelativeStrengthIntradayQualityGrade,
  type RelativeStrengthIntradaySignalGrade,
} from "./relativeStrengthIntraday";

export {
  InstitutionalAccumulationStrategy,
  InstitutionalAccumulationDetector,
  InstitutionalAccumulationValidator,
  InstitutionalAccumulationTradeBuilder,
  buildInstitutionalAccumulationExplainability,
  buildInstitutionalAccumulationInstitutionalScore,
  buildInstitutionalAccumulationSummary,
  calculateConfidence as calculateInstitutionalAccumulationConfidence,
  calculateInstitutionalAccumulationConviction,
  calculateInstitutionalAccumulationEntry,
  calculateInstitutionalAccumulationSignalGrade,
  calculateInstitutionalAccumulationTradeQuality,
  createInstitutionalAccumulationStrategyRegistration,
  detectInstitutionalAccumulation,
  detectTrendStructure as detectInstitutionalAccumulationTrendStructure,
  ensureInstitutionalAccumulationRegistered,
  executeInstitutionalAccumulationThroughEngine,
  executeInstitutionalAccumulationWithPipeline,
  generateInstitutionalAccumulationTargets,
  getInstitutionalAccumulationDetector,
  getInstitutionalAccumulationMetrics,
  getInstitutionalAccumulationTradeBuilder,
  registerInstitutionalAccumulationStrategy,
  resetInstitutionalAccumulationDetector,
  resetInstitutionalAccumulationMetrics,
  resetInstitutionalAccumulationTradeBuilder,
  resolveStopLoss as resolveInstitutionalAccumulationStopLoss,
  validateBreadth as validateInstitutionalAccumulationBreadth,
  validateSector as validateInstitutionalAccumulationSector,
  validateVolume as validateInstitutionalAccumulationVolume,
  DEFAULT_INSTITUTIONAL_ACCUMULATION_CONFIG,
  DEFAULT_INSTITUTIONAL_ACCUMULATION_TRADE_CONFIG,
  INSTITUTIONAL_ACCUMULATION_STRATEGY_ID,
  type InstitutionalAccumulationCandle,
  type InstitutionalAccumulationConfig,
  type InstitutionalAccumulationDetection,
  type InstitutionalAccumulationDetectionContext,
  type InstitutionalAccumulationDirection,
  type InstitutionalAccumulationExplainability,
  type InstitutionalAccumulationInstitutionalScore,
  type InstitutionalAccumulationMarketData,
  type InstitutionalAccumulationMetricsSnapshot,
  type InstitutionalAccumulationPattern,
  type InstitutionalAccumulationStrategyInput,
  type InstitutionalAccumulationTradeConfig,
  type InstitutionalAccumulationTradeSetup,
  type InstitutionalAccumulationQualityGrade,
  type InstitutionalAccumulationSignalGrade,
} from "./institutionalAccumulation";
