/**
 * Foundation seed catalog for Event Intelligence (Sprint 10D.1).
 * Deterministic sample data relative to "today" so all views render content.
 * Replace with live feeds in later sub-sprints — do not wire AI here.
 */

import { DEFAULT_EVENT_TIMEZONE } from "@/constants/eventTypes";
import { addDays, toDateKey } from "@/src/core/events/EventFilters";
import type { EventIntelligenceEvent } from "@/types/event";

function stamp(base: string): { createdAt: string; updatedAt: string } {
  return { createdAt: `${base}T00:00:00.000Z`, updatedAt: `${base}T00:00:00.000Z` };
}

function resolveStatus(
  date: string,
  today: string
): EventIntelligenceEvent["status"] {
  if (date === today) return "today";
  if (date < today) return "completed";
  return "upcoming";
}

/** Build a fresh catalog anchored to the local calendar day. */
export function buildEventSeedCatalog(
  today: string = toDateKey(new Date())
): EventIntelligenceEvent[] {
  const d = (offset: number) => addDays(today, offset);

  const raw: Omit<EventIntelligenceEvent, "status">[] = [
    {
      id: "evt-rbi-policy",
      title: "RBI Monetary Policy Decision",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Monetary Policy",
      exchange: "MACRO",
      eventType: "rbi_policy",
      date: d(0),
      time: "10:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "critical",
      description:
        "Reserve Bank of India MPC rate decision and policy statement.",
      expectedImpact: "High volatility across rates-sensitive sectors",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["Banks", "NBFCs", "Realty"],
      historicalAvailable: true,
      tags: ["rbi", "rates", "mpc"],
      marketCap: "unknown",
      ...stamp(d(0)),
    },
    {
      id: "evt-tcs-q1",
      title: "TCS Q1 FY27 Results",
      company: "Tata Consultancy Services",
      ticker: "TCS",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(0),
      time: "16:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "First quarter financial results and management commentary.",
      expectedImpact: "IT sector sentiment driver",
      marketDirection: "unknown",
      affectedStocks: ["TCS", "INFY", "WIPRO"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: true,
      tags: ["earnings", "it", "nifty50"],
      marketCap: "large",
      ...stamp(d(-2)),
    },
    {
      id: "evt-tcs-call",
      title: "TCS Earnings Conference Call",
      company: "Tata Consultancy Services",
      ticker: "TCS",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "conference_call",
      date: d(1),
      time: "18:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Post-results analyst conference call.",
      expectedImpact: null,
      marketDirection: "neutral",
      affectedStocks: ["TCS"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["call", "earnings"],
      marketCap: "large",
      ...stamp(d(-2)),
    },
    {
      id: "evt-hdfc-div",
      title: "HDFC Bank Interim Dividend",
      company: "HDFC Bank",
      ticker: "HDFCBANK",
      sector: "Financials",
      industry: "Private Banks",
      exchange: "NSE",
      eventType: "dividend",
      date: d(2),
      time: null,
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Board meeting to consider interim dividend.",
      expectedImpact: "Income event for shareholders",
      marketDirection: "neutral",
      affectedStocks: ["HDFCBANK"],
      affectedSectors: ["Financials"],
      historicalAvailable: true,
      tags: ["dividend", "banks"],
      marketCap: "large",
      ...stamp(d(-5)),
    },
    {
      id: "evt-cpi",
      title: "India CPI Inflation Print",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Inflation",
      exchange: "MACRO",
      eventType: "cpi",
      date: d(3),
      time: "17:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "Monthly consumer price inflation release.",
      expectedImpact: "Rates and INR sensitivity",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["Banks", "FMCG", "Consumer Durables"],
      historicalAvailable: true,
      tags: ["cpi", "inflation", "macro"],
      marketCap: "unknown",
      ...stamp(d(-1)),
    },
    {
      id: "evt-reliance-agm",
      title: "Reliance Industries AGM",
      company: "Reliance Industries",
      ticker: "RELIANCE",
      sector: "Energy",
      industry: "Oil & Gas",
      exchange: "NSE",
      eventType: "agm",
      date: d(4),
      time: "14:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Annual General Meeting of shareholders.",
      expectedImpact: null,
      marketDirection: "neutral",
      affectedStocks: ["RELIANCE"],
      affectedSectors: ["Energy", "Telecom", "Retail"],
      historicalAvailable: false,
      tags: ["agm", "governance"],
      marketCap: "large",
      ...stamp(d(-3)),
    },
    {
      id: "evt-ipo-nova",
      title: "NovaTech IPO Opens",
      company: "NovaTech Systems",
      ticker: "NOVATECH",
      sector: "Information Technology",
      industry: "Software Products",
      exchange: "NSE",
      eventType: "ipo",
      date: d(5),
      time: "10:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "IPO subscription window opens for retail and QIBs.",
      expectedImpact: "Primary market liquidity event",
      marketDirection: "bullish",
      affectedStocks: ["NOVATECH"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["ipo", "primary"],
      marketCap: "mid",
      ...stamp(d(-4)),
    },
    {
      id: "evt-fed",
      title: "FOMC Rate Decision",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Monetary Policy",
      exchange: "MACRO",
      eventType: "fed_meeting",
      date: d(6),
      time: "23:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "critical",
      description: "US Federal Reserve interest rate decision and press conference.",
      expectedImpact: "Global risk assets and INR",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["IT", "Metals", "Banks"],
      historicalAvailable: true,
      tags: ["fed", "fomc", "global"],
      marketCap: "unknown",
      ...stamp(d(-2)),
    },
    {
      id: "evt-infosys-buyback",
      title: "Infosys Buyback Record Date",
      company: "Infosys",
      ticker: "INFY",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "buyback",
      date: d(8),
      time: null,
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "Record date for ongoing share buyback programme.",
      expectedImpact: "Supportive for share price near record date",
      marketDirection: "bullish",
      affectedStocks: ["INFY"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: true,
      tags: ["buyback", "it"],
      marketCap: "large",
      ...stamp(d(-6)),
    },
    {
      id: "evt-gdp",
      title: "India GDP Advance Estimates",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Growth",
      exchange: "MACRO",
      eventType: "gdp",
      date: d(10),
      time: "17:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "Quarterly GDP advance estimates from MoSPI.",
      expectedImpact: "Broad market sentiment",
      marketDirection: "unknown",
      affectedStocks: [],
      affectedSectors: ["All"],
      historicalAvailable: true,
      tags: ["gdp", "growth"],
      marketCap: "unknown",
      ...stamp(d(-1)),
    },
    {
      id: "evt-msci",
      title: "MSCI Semi-Annual Index Review",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Index Rebalance",
      exchange: "MACRO",
      eventType: "msci_review",
      date: d(12),
      time: "22:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "critical",
      description: "MSCI announces inclusions, exclusions and weight changes.",
      expectedImpact: "Passive flow impact on reviewed names",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["All"],
      historicalAvailable: true,
      tags: ["msci", "rebalance", "flows"],
      marketCap: "unknown",
      ...stamp(d(-8)),
    },
    {
      id: "evt-maruti-split",
      title: "Maruti Suzuki Stock Split",
      company: "Maruti Suzuki",
      ticker: "MARUTI",
      sector: "Consumer Discretionary",
      industry: "Automobiles",
      exchange: "NSE",
      eventType: "stock_split",
      date: d(14),
      time: null,
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Ex-date for approved equity stock split.",
      expectedImpact: "Liquidity improvement",
      marketDirection: "neutral",
      affectedStocks: ["MARUTI"],
      affectedSectors: ["Automobiles"],
      historicalAvailable: false,
      tags: ["split", "auto"],
      marketCap: "large",
      ...stamp(d(-10)),
    },
    {
      id: "evt-pmi",
      title: "India Manufacturing PMI",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Manufacturing",
      exchange: "MACRO",
      eventType: "pmi",
      date: d(-1),
      time: "10:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "S&P Global India Manufacturing PMI flash/final.",
      expectedImpact: "Cyclical sector cue",
      marketDirection: "neutral",
      affectedStocks: [],
      affectedSectors: ["Industrials", "Metals"],
      historicalAvailable: true,
      tags: ["pmi", "manufacturing"],
      marketCap: "unknown",
      ...stamp(d(-5)),
    },
    {
      id: "evt-sbi-results",
      title: "SBI Q1 FY27 Results",
      company: "State Bank of India",
      ticker: "SBIN",
      sector: "Financials",
      industry: "Public Banks",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(-2),
      time: "14:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "Quarterly results for India's largest public sector bank.",
      expectedImpact: "PSU bank complex cue",
      marketDirection: "unknown",
      affectedStocks: ["SBIN", "BANKBARODA", "PNB"],
      affectedSectors: ["Financials"],
      historicalAvailable: true,
      tags: ["earnings", "banks", "psu"],
      marketCap: "large",
      ...stamp(d(-12)),
    },
    {
      id: "evt-listing-nova",
      title: "NovaTech Exchange Listing",
      company: "NovaTech Systems",
      ticker: "NOVATECH",
      sector: "Information Technology",
      industry: "Software Products",
      exchange: "NSE",
      eventType: "listing",
      date: d(18),
      time: "09:15",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "Expected listing date subject to exchange confirmation.",
      expectedImpact: "Debut price discovery",
      marketDirection: "unknown",
      affectedStocks: ["NOVATECH"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["listing", "ipo"],
      marketCap: "mid",
      ...stamp(d(-4)),
    },
    {
      id: "evt-iip",
      title: "India IIP Release",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Industrial Production",
      exchange: "MACRO",
      eventType: "iip",
      date: d(7),
      time: "17:30",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Index of Industrial Production monthly print.",
      expectedImpact: "Cyclicals sentiment",
      marketDirection: "neutral",
      affectedStocks: [],
      affectedSectors: ["Industrials", "Capital Goods"],
      historicalAvailable: true,
      tags: ["iip", "macro"],
      marketCap: "unknown",
      ...stamp(d(-3)),
    },
    {
      id: "evt-wipro-bonus",
      title: "Wipro Bonus Issue Record Date",
      company: "Wipro",
      ticker: "WIPRO",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "bonus",
      date: d(9),
      time: null,
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Record date for approved bonus share issue.",
      expectedImpact: "Technical adjustment in price",
      marketDirection: "neutral",
      affectedStocks: ["WIPRO"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["bonus", "it"],
      marketCap: "large",
      ...stamp(d(-7)),
    },
    {
      id: "evt-ftse",
      title: "FTSE India Index Review",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Index Rebalance",
      exchange: "MACRO",
      eventType: "ftse_review",
      date: d(20),
      time: "18:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "high",
      description: "FTSE Russell index review for India constituents.",
      expectedImpact: "Passive flow adjustments",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["All"],
      historicalAvailable: true,
      tags: ["ftse", "rebalance"],
      marketCap: "unknown",
      ...stamp(d(-9)),
    },
    {
      id: "evt-trade-balance",
      title: "India Merchandise Trade Balance",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Trade",
      exchange: "MACRO",
      eventType: "trade_balance",
      date: d(11),
      time: "17:00",
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "low",
      description: "Monthly merchandise exports and imports print.",
      expectedImpact: "INR and export-oriented sectors",
      marketDirection: "neutral",
      affectedStocks: [],
      affectedSectors: ["IT", "Pharma", "Textiles"],
      historicalAvailable: true,
      tags: ["trade", "exports"],
      marketCap: "unknown",
      ...stamp(d(-2)),
    },
    {
      id: "evt-rights-small",
      title: "Aether Industries Rights Issue",
      company: "Aether Industries",
      ticker: "AETHER",
      sector: "Materials",
      industry: "Specialty Chemicals",
      exchange: "NSE",
      eventType: "rights_issue",
      date: d(15),
      time: null,
      timezone: DEFAULT_EVENT_TIMEZONE,
      importance: "medium",
      description: "Rights issue opens for eligible shareholders.",
      expectedImpact: "Dilution and capital raise",
      marketDirection: "mixed",
      affectedStocks: ["AETHER"],
      affectedSectors: ["Materials"],
      historicalAvailable: false,
      tags: ["rights", "chemicals"],
      marketCap: "small",
      ...stamp(d(-11)),
    },
  ];

  return raw.map((event) => ({
    ...event,
    status: resolveStatus(event.date, today),
  }));
}
