import { fetchCompanyProfile } from "@/services/companyData";
import { fetchCompanyResearch } from "@/services/researchData";
import { fetchFundamentalsBundle } from "@/lib/fundamentals";
import type { FundamentalsBundle } from "@/lib/fundamentals/types";
import { EquityIntelligenceEngine } from "@/lib/engine";
import { CACHE_TTL } from "@/lib/cache";
import {
  amountToCrore,
  metricHistory,
  round,
  toneForScore,
  verdictForScore,
} from "@/lib/engine/utils";
import { createRng, hashSeed } from "@/lib/random";
import { getCached, cacheKey } from "@/lib/cache";
import type {
  CompanyProfile,
  CompanyResearch,
  CompanyTimelineEvent,
  EquityIntelligence,
  EquityScore,
  FinancialHealthMetric,
  InstitutionalPeer,
  QuarterlyAnalysis,
} from "@/types";

function buildFinancialHealth(profile: CompanyProfile): FinancialHealthMetric[] {
  const financials = profile.financials;
  const ff = profile.fundamentals;
  const annualChronological = [...profile.annualFinancials].reverse();
  const revenueHistory = annualChronological.map((item) => amountToCrore(item.revenue));
  const profitHistory = annualChronological.map((item) => amountToCrore(item.netProfit));
  const epsHistory = annualChronological.map((item) => item.eps);
  const quarterlyMargins = [...profile.quarterlyResults].reverse().map((item) => item.margin);
  const revenueCr = amountToCrore(financials.revenue);
  const operatingCashFlow =
    ff?.fcf && ff.fcf !== "—"
      ? amountToCrore(ff.fcf)
      : Math.round(revenueCr * (0.1 + Math.min(financials.roce, 30) / 300));
  const freeCashFlow =
    ff?.fcf && ff.fcf !== "—"
      ? amountToCrore(ff.fcf)
      : Math.round(operatingCashFlow * (0.48 + Math.min(financials.roe, 30) / 100));
  const workingCapitalDays = Math.max(18, Math.round(82 - financials.roce * 1.8));
  const operatingMargin = ff?.operatingMargin ?? round((profile.quarterlyResults[0]?.margin ?? 0) + 4);
  const roe = ff?.roe ?? financials.roe;
  const roce = ff?.roce ?? financials.roce;
  const debtEquity = ff?.debtEquity ?? financials.debtToEquity;
  const revenueGrowth = ff?.revenueCagr ?? financials.revenueGrowth;
  const profitGrowth = ff?.profitCagr ?? financials.netProfitGrowth;
  const cashConversion = ff?.cashConversion;

  return [
    {
      key: "revenue",
      label: "Revenue Trend",
      value: financials.revenue,
      trend: revenueGrowth >= 0 ? "up" : "down",
      trendLabel: `${revenueGrowth > 0 ? "+" : ""}${revenueGrowth}% YoY`,
      explanation: "Top-line trajectory across reported periods.",
      history: revenueHistory,
    },
    {
      key: "profit",
      label: "Profit Trend",
      value: financials.netProfit,
      trend: profitGrowth >= 0 ? "up" : "down",
      trendLabel: `${profitGrowth > 0 ? "+" : ""}${profitGrowth}% YoY`,
      explanation: "Net earnings growth and operating leverage.",
      history: profitHistory,
    },
    {
      key: "eps",
      label: "EPS Trend",
      value: ff?.eps !== null && ff?.eps !== undefined ? `₹${ff.eps}` : `₹${profile.annualFinancials[0]?.eps ?? 0}`,
      trend: epsHistory.at(-1)! >= epsHistory[0] ? "up" : "down",
      trendLabel: "3-year progression",
      explanation: "Per-share earnings compounding after dilution.",
      history: epsHistory,
    },
    {
      key: "margin",
      label: "Operating Margin",
      value: `${operatingMargin}%`,
      trend: quarterlyMargins.at(-1)! >= quarterlyMargins[0] ? "up" : "down",
      trendLabel: `${round((quarterlyMargins.at(-1)! - quarterlyMargins[0]) * 100, 0)} bps`,
      explanation: "Operating efficiency before interest and tax.",
      history: quarterlyMargins.map((margin) => round(margin + 4)),
    },
    {
      key: "roe",
      label: "ROE",
      value: `${roe}%`,
      trend: roe >= 15 ? "up" : "stable",
      trendLabel: roe >= 20 ? "High quality" : "Monitor",
      explanation: "Profit generated on shareholder equity.",
      history: metricHistory(roe, 3.2),
    },
    {
      key: "roce",
      label: "ROCE",
      value: `${roce}%`,
      trend: roce >= 15 ? "up" : "stable",
      trendLabel: roce > 20 ? "Above 20%" : "Below 20%",
      explanation: "Efficiency of total capital employed.",
      history: metricHistory(roce, 2.4),
    },
    {
      key: "debt",
      label: "Debt",
      value: `${debtEquity}x`,
      trend: debtEquity <= (profile.sector === "Banking" ? 7 : 0.8) ? "down" : "up",
      trendLabel: "Debt / Equity",
      explanation: "Balance-sheet leverage relative to equity.",
      history: metricHistory(debtEquity, -3),
    },
    {
      key: "cash-flow",
      label: "Cash Flow",
      value: `₹${operatingCashFlow.toLocaleString("en-IN")} Cr`,
      trend: "up",
      trendLabel: "Operating cash flow",
      explanation: "Cash generated by core operations.",
      history: metricHistory(operatingCashFlow, revenueGrowth * 0.7),
    },
    {
      key: "free-cash-flow",
      label: "Free Cash Flow",
      value: ff?.fcf && ff.fcf !== "—" ? ff.fcf : `₹${freeCashFlow.toLocaleString("en-IN")} Cr`,
      trend: freeCashFlow > 0 ? "up" : "down",
      trendLabel: cashConversion !== null
        ? `${cashConversion}% conversion`
        : `${Math.round((freeCashFlow / operatingCashFlow) * 100)}% conversion`,
      explanation: "Cash available after capital expenditure.",
      history: metricHistory(freeCashFlow, profitGrowth * 0.65),
    },
    {
      key: "working-capital",
      label: "Working Capital",
      value: `${workingCapitalDays} days`,
      trend: workingCapitalDays < 60 ? "down" : "stable",
      trendLabel: workingCapitalDays < 60 ? "Efficient" : "Stable",
      explanation: "Estimated cash conversion and funding cycle.",
      history: metricHistory(workingCapitalDays, -2.5),
    },
  ];
}

function buildPeers(profile: CompanyProfile, rng: () => number): InstitutionalPeer[] {
  const current: InstitutionalPeer = {
    symbol: profile.symbol,
    name: profile.name,
    isCompany: true,
    pe: profile.financials.pe,
    pb: profile.financials.pb,
    roe: profile.financials.roe,
    roce: profile.financials.roce,
    salesGrowth: profile.financials.revenueGrowth,
    profitGrowth: profile.financials.netProfitGrowth,
    debt: profile.financials.debtToEquity,
    marketCap: profile.marketCap,
    valuation: profile.financials.pe < 22 ? "Attractive" : profile.financials.pe < 35 ? "Fair" : "Premium",
    industryRank: 1,
  };

  const peers = profile.peers.map((peer, index): InstitutionalPeer => {
    const qualityBias = 0.75 + rng() * 0.45;
    const pb = round(Math.max(0.8, peer.pe / (4.5 + rng() * 5)));
    const roe = round(Math.min(48, Math.max(6, profile.financials.roe * qualityBias)));
    const roce = round(Math.min(52, Math.max(5, profile.financials.roce * (0.8 + rng() * 0.5))));
    const salesGrowth = round(Math.min(35, Math.max(1, profile.financials.revenueGrowth * (0.65 + rng() * 0.75))));
    const profitGrowth = round(Math.min(60, Math.max(-5, profile.financials.netProfitGrowth * (0.55 + rng() * 0.9))));
    const debt = round(Math.max(0.02, profile.financials.debtToEquity * (0.55 + rng() * 1.05)), 2);

    return {
      symbol: peer.symbol,
      name: peer.name,
      isCompany: false,
      pe: peer.pe,
      pb,
      roe,
      roce,
      salesGrowth,
      profitGrowth,
      debt,
      marketCap: peer.marketCap,
      valuation: peer.pe < 22 ? "Attractive" : peer.pe < 35 ? "Fair" : "Premium",
      industryRank: index + 2,
    };
  });

  return [current, ...peers]
    .sort(
      (left, right) =>
        right.roe + right.roce + right.profitGrowth - (left.roe + left.roce + left.profitGrowth)
    )
    .map((peer, index) => ({ ...peer, industryRank: index + 1 }));
}

function buildQuarterly(profile: CompanyProfile): QuarterlyAnalysis {
  const chronological = [...profile.quarterlyResults].reverse();
  const points = chronological.map((quarter, index) => {
    const previous = chronological[index - 1];
    const revenue = amountToCrore(quarter.revenue);
    const profit = amountToCrore(quarter.netProfit);
    const previousRevenue = previous ? amountToCrore(previous.revenue) : revenue;
    const previousProfit = previous ? amountToCrore(previous.netProfit) : profit;

    return {
      quarter: quarter.quarter,
      revenue: quarter.revenue,
      profit: quarter.netProfit,
      eps: quarter.eps,
      margin: quarter.margin,
      revenueGrowth: previous ? round(((revenue - previousRevenue) / previousRevenue) * 100) : 0,
      profitGrowth: previous ? round(((profit - previousProfit) / previousProfit) * 100) : 0,
    };
  });
  const latest = points.at(-1)!;

  return {
    points,
    summary: `${profile.name}'s latest quarter shows ${latest.revenueGrowth >= 0 ? "improving" : "moderating"} revenue momentum and ${latest.profitGrowth >= latest.revenueGrowth ? "positive operating leverage" : "some margin pressure"}. EPS reached ₹${latest.eps} while net margin settled at ${latest.margin}%.`,
  };
}

function buildTimeline(profile: CompanyProfile, bundleTimeline?: CompanyTimelineEvent[]): CompanyTimelineEvent[] {
  if (bundleTimeline?.length) {
    return bundleTimeline;
  }

  const latest = profile.quarterlyResults[0];
  return [
    {
      id: "results",
      date: "18 Jul 2026",
      type: "Results",
      title: `${latest.quarter} results`,
      description: `Revenue ${latest.revenue}, profit ${latest.netProfit} and EPS ₹${latest.eps}.`,
    },
    {
      id: "dividend",
      date: "04 Jul 2026",
      type: "Dividend",
      title: "Final dividend announced",
      description: "Board recommended a final dividend, subject to shareholder approval.",
    },
    {
      id: "acquisition",
      date: "21 May 2026",
      type: "Acquisition",
      title: "Strategic investment approved",
      description: `Investment expands capabilities across the ${profile.industry} value chain.`,
    },
    {
      id: "management",
      date: "09 Apr 2026",
      type: "Management Change",
      title: "Senior leadership appointment",
      description: "Leadership mandate focuses on execution, digital capability and capital discipline.",
    },
    {
      id: "corporate",
      date: "28 Mar 2026",
      type: "Corporate Action",
      title: "Investor presentation filed",
      description: "Management reiterated medium-term growth and margin priorities.",
    },
    {
      id: "bonus",
      date: "12 Feb 2026",
      type: "Bonus",
      title: "Bonus issue reviewed",
      description: "Capital allocation committee reviewed shareholder distribution alternatives.",
    },
    {
      id: "split",
      date: "16 Jan 2026",
      type: "Split",
      title: "Share liquidity assessment",
      description: "Board assessed face-value structure and market liquidity.",
    },
  ];
}

function buildEquityIntelligence(
  profile: CompanyProfile,
  bundleTimeline?: CompanyTimelineEvent[],
  bundle?: FundamentalsBundle,
  research?: CompanyResearch | null
): EquityIntelligence {
  const rng = createRng(hashSeed(`sprint-5-${profile.symbol}`));
  const fundamentals = profile.fundamentals;
  const ctx = EquityIntelligenceEngine.createAnalysisContext(profile, bundle, fundamentals);

  const scoreBundle = EquityIntelligenceEngine.calculateEquityScores(profile);
  const score = EquityIntelligenceEngine.toEquityScore(scoreBundle);

  const financialQuality = EquityIntelligenceEngine.calculateFinancialQuality(ctx);
  const valuation = EquityIntelligenceEngine.calculateValuation(ctx);
  const multiYearTrends = EquityIntelligenceEngine.calculateMultiYearTrends(ctx);
  const redFlags = EquityIntelligenceEngine.detectRedFlags(ctx, valuation);
  const opportunities = EquityIntelligenceEngine.detectOpportunities(ctx);
  const researchConfidence = EquityIntelligenceEngine.calculateResearchConfidence(
    ctx,
    score,
    financialQuality,
    valuation,
    research?.technicals.score
  );
  const thesis = EquityIntelligenceEngine.buildInvestmentThesis(
    ctx,
    score,
    financialQuality,
    valuation,
    redFlags,
    research?.technicals.score,
    opportunities
  );

  const { checklist } = EquityIntelligenceEngine.calculateChecklist(profile, score);

  const { decision } = EquityIntelligenceEngine.buildDecisionAnalysis({
    ctx,
    equityScore: score,
    financialQuality,
    valuation,
    researchConfidence,
    thesis,
    redFlags,
    opportunities,
    checklist,
    research,
  });

  const summary = {
    verdict: decision.verdict,
    summary: decision.aiSummary.institutionalSummary,
    reasons: decision.aiSummary.whyBuy.slice(0, 3),
  };

  const dataTransparency = EquityIntelligenceEngine.buildDataTransparency({
    provider: bundle?.provider ?? "Mock Provider",
    source: bundle?.source ?? "mock",
    fetchedAt: bundle?.fetchedAt ?? new Date().toISOString(),
    dataSource: "Financial Fundamentals & Research Engine",
    ttlMs: CACHE_TTL.RESEARCH,
  });

  const freshnessLabel =
    dataTransparency.freshness === "live"
      ? "Live"
      : dataTransparency.freshness === "delayed"
        ? "Delayed"
        : "Mock";

  return {
    generatedAt: `${freshnessLabel} · ${dataTransparency.provider} · ${dataTransparency.cacheAge}`,
    score,
    thesis,
    decision,
    financialHealth: buildFinancialHealth(profile),
    peers: buildPeers(profile, rng),
    quarterly: buildQuarterly(profile),
    summary,
    checklist,
    timeline: buildTimeline(profile, bundleTimeline),
    financialQuality,
    valuation,
    multiYearTrends,
    redFlags,
    opportunities,
    researchConfidence,
    dataTransparency,
  };
}

export async function fetchEquityIntelligence(
  symbol: string
): Promise<EquityIntelligence | null> {
  return getCached(
    { key: cacheKey("equity-intelligence", symbol), ttlMs: CACHE_TTL.RESEARCH },
    async () => {
      const profile = await fetchCompanyProfile(symbol);
      if (!profile) return null;
      const [fundamentals, research] = await Promise.all([
        fetchFundamentalsBundle(symbol),
        fetchCompanyResearch(symbol),
      ]);
      return buildEquityIntelligence(
        profile,
        fundamentals?.data.timeline,
        fundamentals?.data,
        research
      );
    }
  );
}

export { toneForScore, verdictForScore };
