import type { CompanyProfile } from "@/types";

/** Static fundamentals seed data — terminal fallback for Sprint 7B. */
export const MOCK_COMPANY_SEEDS: Record<string, Omit<CompanyProfile, "priceHistory">> = {
  RELIANCE: {
    symbol: "RELIANCE",
    name: "Reliance Industries Ltd",
    price: 2890.5,
    change: 35.4,
    changePercent: 1.24,
    marketCap: "₹19.5L Cr",
    sector: "Conglomerate",
    industry: "Oil & Gas / Retail / Telecom",
    description:
      "Reliance Industries is India's largest private sector company with interests spanning energy, petrochemicals, retail, digital services, and new energy. Jio Platforms and Reliance Retail are key growth drivers.",
    website: "ril.com",
    founded: "1973",
    employees: "3,89,000+",
    financials: {
      revenue: "₹9.74L Cr",
      revenueGrowth: 11.2,
      netProfit: "₹79,020 Cr",
      netProfitGrowth: 8.4,
      roe: 12.8,
      roce: 10.5,
      pe: 27.4,
      pb: 2.1,
      debtToEquity: 0.42,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹2.58L Cr", netProfit: "₹21,930 Cr", eps: 16.2, margin: 8.5 },
      { quarter: "Q3 FY25", revenue: "₹2.48L Cr", netProfit: "₹20,150 Cr", eps: 14.9, margin: 8.1 },
      { quarter: "Q2 FY25", revenue: "₹2.42L Cr", netProfit: "₹19,280 Cr", eps: 14.2, margin: 8.0 },
      { quarter: "Q1 FY25", revenue: "₹2.26L Cr", netProfit: "₹17,660 Cr", eps: 13.1, margin: 7.8 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹9.74L Cr", netProfit: "₹79,020 Cr", eps: 58.4, roe: 12.8 },
      { year: "FY24", revenue: "₹9.00L Cr", netProfit: "₹72,880 Cr", eps: 53.8, roe: 12.1 },
      { year: "FY23", revenue: "₹8.35L Cr", netProfit: "₹66,702 Cr", eps: 49.2, roe: 11.5 },
    ],
    shareholding: { promoter: 50.39, fii: 23.12, dii: 14.85, public: 11.64, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "ADANIENT", name: "Adani Enterprises", price: 2845.2, changePercent: 2.24, pe: 85.2, marketCap: "₹3.2L Cr" },
      { symbol: "TATASTEEL", name: "Tata Steel", price: 142.8, changePercent: 0.92, pe: 18.4, marketCap: "₹1.8L Cr" },
      { symbol: "ONGC", name: "ONGC", price: 268.4, changePercent: -0.35, pe: 9.8, marketCap: "₹3.4L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "27.4x", industryAvg: "22.1x", status: "overvalued" },
      { label: "P/B Ratio", value: "2.1x", industryAvg: "1.8x", status: "fair" },
      { label: "EV/EBITDA", value: "12.8x", industryAvg: "10.5x", status: "overvalued" },
      { label: "Dividend Yield", value: "0.35%", industryAvg: "1.2%", status: "undervalued" },
    ],
    news: [
      { id: "1", title: "Reliance Jio adds 4.2M subscribers in March quarter", source: "Economic Times", timestamp: "3 hours ago", summary: "Jio continues market share gains with aggressive 5G rollout across tier-2 cities." },
      { id: "2", title: "RIL green energy capex crosses ₹75,000 Cr milestone", source: "Mint", timestamp: "1 day ago", summary: "New energy investments accelerate with solar giga-factory commissioning." },
    ],
    notes: [
      { id: "1", content: "Strong retail momentum — watch Q1 FY26 store additions.", createdAt: "2026-06-28" },
    ],
  },
  TCS: {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    price: 4125.8,
    change: 34.8,
    changePercent: 0.85,
    marketCap: "₹15.0L Cr",
    sector: "IT",
    industry: "IT Services & Consulting",
    description:
      "TCS is India's largest IT services company and a global leader in digital transformation, cloud, and consulting. It serves clients across banking, retail, healthcare, and manufacturing.",
    website: "tcs.com",
    founded: "1968",
    employees: "6,00,000+",
    financials: {
      revenue: "₹2.40L Cr",
      revenueGrowth: 9.8,
      netProfit: "₹46,585 Cr",
      netProfitGrowth: 10.2,
      roe: 48.5,
      roce: 52.3,
      pe: 32.1,
      pb: 12.4,
      debtToEquity: 0.05,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹62,980 Cr", netProfit: "₹12,760 Cr", eps: 35.1, margin: 20.3 },
      { quarter: "Q3 FY25", revenue: "₹60,210 Cr", netProfit: "₹11,910 Cr", eps: 32.8, margin: 19.8 },
      { quarter: "Q2 FY25", revenue: "₹59,380 Cr", netProfit: "₹11,380 Cr", eps: 31.3, margin: 19.2 },
      { quarter: "Q1 FY25", revenue: "₹57,480 Cr", netProfit: "₹11,535 Cr", eps: 31.7, margin: 20.1 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹2.40L Cr", netProfit: "₹46,585 Cr", eps: 127.4, roe: 48.5 },
      { year: "FY24", revenue: "₹2.19L Cr", netProfit: "₹42,282 Cr", eps: 115.6, roe: 46.2 },
      { year: "FY23", revenue: "₹2.06L Cr", netProfit: "₹38,449 Cr", eps: 105.1, roe: 44.8 },
    ],
    shareholding: { promoter: 71.77, fii: 12.45, dii: 10.82, public: 4.96, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "INFY", name: "Infosys", price: 1892.15, changePercent: 1.56, pe: 28.4, marketCap: "₹7.8L Cr" },
      { symbol: "WIPRO", name: "Wipro", price: 285.6, changePercent: -0.75, pe: 22.1, marketCap: "₹1.5L Cr" },
      { symbol: "HCLTECH", name: "HCL Technologies", price: 1842.3, changePercent: 0.62, pe: 26.8, marketCap: "₹5.0L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "32.1x", industryAvg: "28.5x", status: "overvalued" },
      { label: "P/B Ratio", value: "12.4x", industryAvg: "7.2x", status: "overvalued" },
      { label: "EV/EBITDA", value: "24.2x", industryAvg: "20.1x", status: "overvalued" },
      { label: "Dividend Yield", value: "1.35%", industryAvg: "1.8%", status: "fair" },
    ],
    news: [
      { id: "1", title: "TCS wins $2.1B deal from European financial services giant", source: "Business Standard", timestamp: "5 hours ago", summary: "Multi-year digital transformation deal expected to boost FY26 revenue growth." },
      { id: "2", title: "TCS expands AI.Cloud unit with 40,000 upskilled employees", source: "Mint", timestamp: "2 days ago", summary: "GenAI practice revenue grew 3.2x YoY in the latest quarter." },
    ],
    notes: [],
  },
  HDFCBANK: {
    symbol: "HDFCBANK",
    name: "HDFC Bank Ltd",
    price: 1724.3,
    change: -7.28,
    changePercent: -0.42,
    marketCap: "₹13.2L Cr",
    sector: "Banking",
    industry: "Private Sector Bank",
    description:
      "HDFC Bank is India's largest private sector bank by market capitalization, offering retail banking, wholesale banking, treasury, and other financial services.",
    website: "hdfcbank.com",
    founded: "1994",
    employees: "2,10,000+",
    financials: {
      revenue: "₹2.68L Cr",
      revenueGrowth: 18.5,
      netProfit: "₹67,347 Cr",
      netProfitGrowth: 12.1,
      roe: 16.2,
      roce: 7.8,
      pe: 19.6,
      pb: 2.8,
      debtToEquity: 5.2,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹72,450 Cr", netProfit: "₹18,120 Cr", eps: 23.6, margin: 25.0 },
      { quarter: "Q3 FY25", revenue: "₹68,920 Cr", netProfit: "₹16,840 Cr", eps: 21.9, margin: 24.4 },
      { quarter: "Q2 FY25", revenue: "₹66,180 Cr", netProfit: "₹16,210 Cr", eps: 21.1, margin: 24.5 },
      { quarter: "Q1 FY25", revenue: "₹61,450 Cr", netProfit: "₹16,177 Cr", eps: 21.0, margin: 26.3 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹2.68L Cr", netProfit: "₹67,347 Cr", eps: 87.6, roe: 16.2 },
      { year: "FY24", revenue: "₹2.26L Cr", netProfit: "₹60,812 Cr", eps: 79.1, roe: 15.8 },
      { year: "FY23", revenue: "₹1.98L Cr", netProfit: "₹44,109 Cr", eps: 80.2, roe: 17.1 },
    ],
    shareholding: { promoter: 0.0, fii: 32.18, dii: 38.42, public: 29.4, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "ICICIBANK", name: "ICICI Bank", price: 1285.4, changePercent: 0.32, pe: 18.2, marketCap: "₹9.1L Cr" },
      { symbol: "SBIN", name: "State Bank of India", price: 812.35, changePercent: -0.64, pe: 10.4, marketCap: "₹7.3L Cr" },
      { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", price: 1982.5, changePercent: 0.18, pe: 20.8, marketCap: "₹3.9L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "19.6x", industryAvg: "16.8x", status: "overvalued" },
      { label: "P/B Ratio", value: "2.8x", industryAvg: "2.1x", status: "overvalued" },
      { label: "Price/Book", value: "2.8x", industryAvg: "2.1x", status: "overvalued" },
      { label: "Dividend Yield", value: "1.12%", industryAvg: "0.9%", status: "fair" },
    ],
    news: [
      { id: "1", title: "HDFC Bank credit growth accelerates to 15.2% YoY", source: "Moneycontrol", timestamp: "4 hours ago", summary: "Retail loan book expansion drives net interest income beat in Q4." },
    ],
    notes: [],
  },
  INFY: {
    symbol: "INFY",
    name: "Infosys Ltd",
    price: 1892.15,
    change: 29.05,
    changePercent: 1.56,
    marketCap: "₹7.8L Cr",
    sector: "IT",
    industry: "IT Services & Consulting",
    description:
      "Infosys is a global leader in next-generation digital services and consulting, enabling clients in 56 countries to navigate digital transformation.",
    website: "infosys.com",
    founded: "1981",
    employees: "3,20,000+",
    financials: {
      revenue: "₹1.62L Cr",
      revenueGrowth: 7.2,
      netProfit: "₹26,763 Cr",
      netProfitGrowth: 6.8,
      roe: 28.4,
      roce: 32.1,
      pe: 28.4,
      pb: 7.2,
      debtToEquity: 0.08,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹41,280 Cr", netProfit: "₹6,920 Cr", eps: 16.6, margin: 16.8 },
      { quarter: "Q3 FY25", revenue: "₹40,120 Cr", netProfit: "₹6,810 Cr", eps: 16.3, margin: 17.0 },
      { quarter: "Q2 FY25", revenue: "₹39,580 Cr", netProfit: "₹6,516 Cr", eps: 15.6, margin: 16.5 },
      { quarter: "Q1 FY25", revenue: "₹40,520 Cr", netProfit: "₹6,517 Cr", eps: 15.6, margin: 16.1 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹1.62L Cr", netProfit: "₹26,763 Cr", eps: 64.1, roe: 28.4 },
      { year: "FY24", revenue: "₹1.51L Cr", netProfit: "₹25,053 Cr", eps: 60.0, roe: 27.2 },
      { year: "FY23", revenue: "₹1.47L Cr", netProfit: "₹24,095 Cr", eps: 57.7, roe: 26.8 },
    ],
    shareholding: { promoter: 14.61, fii: 33.82, dii: 38.45, public: 13.12, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "TCS", name: "Tata Consultancy Services", price: 4125.8, changePercent: 0.85, pe: 32.1, marketCap: "₹15.0L Cr" },
      { symbol: "WIPRO", name: "Wipro", price: 285.6, changePercent: -0.75, pe: 22.1, marketCap: "₹1.5L Cr" },
      { symbol: "TECHM", name: "Tech Mahindra", price: 1682.4, changePercent: 0.45, pe: 34.2, marketCap: "₹1.6L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "28.4x", industryAvg: "28.5x", status: "fair" },
      { label: "P/B Ratio", value: "7.2x", industryAvg: "7.2x", status: "fair" },
      { label: "EV/EBITDA", value: "21.8x", industryAvg: "20.1x", status: "overvalued" },
      { label: "Dividend Yield", value: "2.45%", industryAvg: "1.8%", status: "undervalued" },
    ],
    news: [
      { id: "1", title: "Infosys raises FY26 revenue guidance on strong deal pipeline", source: "Reuters", timestamp: "6 hours ago", summary: "Large deal wins in BFSI and retail verticals drive upgraded outlook." },
    ],
    notes: [],
  },
  ICICIBANK: {
    symbol: "ICICIBANK",
    name: "ICICI Bank Ltd",
    price: 1285.4,
    change: 4.1,
    changePercent: 0.32,
    marketCap: "₹9.1L Cr",
    sector: "Banking",
    industry: "Private Sector Bank",
    description:
      "ICICI Bank is a leading private sector bank in India offering a wide range of banking products and financial services to corporate and retail customers.",
    website: "icicibank.com",
    founded: "1994",
    employees: "1,30,000+",
    financials: {
      revenue: "₹1.85L Cr",
      revenueGrowth: 14.8,
      netProfit: "₹42,384 Cr",
      netProfitGrowth: 15.6,
      roe: 17.8,
      roce: 7.2,
      pe: 18.2,
      pb: 3.1,
      debtToEquity: 4.8,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹50,820 Cr", netProfit: "₹11,240 Cr", eps: 15.9, margin: 22.1 },
      { quarter: "Q3 FY25", revenue: "₹47,620 Cr", netProfit: "₹10,480 Cr", eps: 14.8, margin: 22.0 },
      { quarter: "Q2 FY25", revenue: "₹45,180 Cr", netProfit: "₹10,120 Cr", eps: 14.3, margin: 22.4 },
      { quarter: "Q1 FY25", revenue: "₹42,380 Cr", netProfit: "₹10,544 Cr", eps: 14.9, margin: 24.9 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹1.85L Cr", netProfit: "₹42,384 Cr", eps: 59.9, roe: 17.8 },
      { year: "FY24", revenue: "₹1.61L Cr", netProfit: "₹36,663 Cr", eps: 51.8, roe: 17.2 },
      { year: "FY23", revenue: "₹1.42L Cr", netProfit: "₹31,896 Cr", eps: 45.1, roe: 16.5 },
    ],
    shareholding: { promoter: 0.0, fii: 42.18, dii: 35.62, public: 22.2, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "HDFCBANK", name: "HDFC Bank", price: 1724.3, changePercent: -0.42, pe: 19.6, marketCap: "₹13.2L Cr" },
      { symbol: "SBIN", name: "State Bank of India", price: 812.35, changePercent: -0.64, pe: 10.4, marketCap: "₹7.3L Cr" },
      { symbol: "AXISBANK", name: "Axis Bank", price: 1182.6, changePercent: 0.55, pe: 14.2, marketCap: "₹3.6L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "18.2x", industryAvg: "16.8x", status: "overvalued" },
      { label: "P/B Ratio", value: "3.1x", industryAvg: "2.1x", status: "overvalued" },
      { label: "ROE", value: "17.8%", industryAvg: "15.2%", status: "undervalued" },
      { label: "Dividend Yield", value: "0.82%", industryAvg: "0.9%", status: "fair" },
    ],
    news: [
      { id: "1", title: "ICICI Bank retail deposits grow 16% YoY", source: "Economic Times", timestamp: "8 hours ago", summary: "CASA ratio improvement supports margin expansion in Q4." },
    ],
    notes: [],
  },
  BHARTIARTL: {
    symbol: "BHARTIARTL",
    name: "Bharti Airtel Ltd",
    price: 1685.4,
    change: 24.6,
    changePercent: 1.48,
    marketCap: "₹9.8L Cr",
    sector: "Telecom",
    industry: "Telecommunications",
    description:
      "Bharti Airtel is India's second-largest telecom operator providing mobile, broadband, and enterprise services across South Asia and Africa.",
    website: "airtel.in",
    founded: "1995",
    employees: "25,000+",
    financials: {
      revenue: "₹1.58L Cr",
      revenueGrowth: 12.4,
      netProfit: "₹14,781 Cr",
      netProfitGrowth: 95.2,
      roe: 12.4,
      roce: 11.8,
      pe: 66.2,
      pb: 8.4,
      debtToEquity: 1.82,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹41,200 Cr", netProfit: "₹4,250 Cr", eps: 7.2, margin: 10.3 },
      { quarter: "Q3 FY25", revenue: "₹39,800 Cr", netProfit: "₹3,980 Cr", eps: 6.7, margin: 10.0 },
      { quarter: "Q2 FY25", revenue: "₹38,450 Cr", netProfit: "₹3,720 Cr", eps: 6.3, margin: 9.7 },
      { quarter: "Q1 FY25", revenue: "₹38,550 Cr", netProfit: "₹2,831 Cr", eps: 4.8, margin: 7.3 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹1.58L Cr", netProfit: "₹14,781 Cr", eps: 24.0, roe: 12.4 },
      { year: "FY24", revenue: "₹1.41L Cr", netProfit: "₹7,572 Cr", eps: 12.3, roe: 7.2 },
      { year: "FY23", revenue: "₹1.36L Cr", netProfit: "₹8,345 Cr", eps: 13.5, roe: 8.1 },
    ],
    shareholding: { promoter: 55.93, fii: 18.42, dii: 16.28, public: 9.37, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "RELIANCE", name: "Reliance Industries", price: 2890.5, changePercent: 1.24, pe: 27.4, marketCap: "₹19.5L Cr" },
      { symbol: "IDEA", name: "Vodafone Idea", price: 12.8, changePercent: -1.2, pe: 0, marketCap: "₹1.4L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "66.2x", industryAvg: "45.0x", status: "overvalued" },
      { label: "P/B Ratio", value: "8.4x", industryAvg: "5.2x", status: "overvalued" },
      { label: "EV/EBITDA", value: "14.2x", industryAvg: "11.8x", status: "overvalued" },
      { label: "ARPU Growth", value: "12.4%", industryAvg: "8.5%", status: "undervalued" },
    ],
    news: [
      { id: "1", title: "Airtel 5G subscribers cross 120M milestone", source: "Mint", timestamp: "2 hours ago", summary: "Premium ARPU growth continues as 5G monetization accelerates." },
    ],
    notes: [],
  },
  SBIN: {
    symbol: "SBIN",
    name: "State Bank of India",
    price: 812.35,
    change: -5.2,
    changePercent: -0.64,
    marketCap: "₹7.3L Cr",
    sector: "Banking",
    industry: "Public Sector Bank",
    description:
      "State Bank of India is India's largest public sector bank, offering comprehensive banking and financial services across retail, corporate, and international segments.",
    website: "sbi.co.in",
    founded: "1955",
    employees: "2,50,000+",
    financials: {
      revenue: "₹4.52L Cr",
      revenueGrowth: 10.2,
      netProfit: "₹61,077 Cr",
      netProfitGrowth: 6.8,
      roe: 18.2,
      roce: 6.4,
      pe: 10.4,
      pb: 1.6,
      debtToEquity: 8.2,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹1.18L Cr", netProfit: "₹18,420 Cr", eps: 20.6, margin: 15.6 },
      { quarter: "Q3 FY25", revenue: "₹1.12L Cr", netProfit: "₹15,820 Cr", eps: 17.7, margin: 14.1 },
      { quarter: "Q2 FY25", revenue: "₹1.10L Cr", netProfit: "₹14,920 Cr", eps: 16.7, margin: 13.6 },
      { quarter: "Q1 FY25", revenue: "₹1.12L Cr", netProfit: "₹11,915 Cr", eps: 13.3, margin: 10.6 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹4.52L Cr", netProfit: "₹61,077 Cr", eps: 68.3, roe: 18.2 },
      { year: "FY24", revenue: "₹4.10L Cr", netProfit: "₹57,192 Cr", eps: 63.9, roe: 18.8 },
      { year: "FY23", revenue: "₹3.68L Cr", netProfit: "₹50,232 Cr", eps: 56.1, roe: 17.5 },
    ],
    shareholding: { promoter: 55.5, fii: 10.82, dii: 22.45, public: 11.23, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "HDFCBANK", name: "HDFC Bank", price: 1724.3, changePercent: -0.42, pe: 19.6, marketCap: "₹13.2L Cr" },
      { symbol: "ICICIBANK", name: "ICICI Bank", price: 1285.4, changePercent: 0.32, pe: 18.2, marketCap: "₹9.1L Cr" },
      { symbol: "PNB", name: "Punjab National Bank", price: 108.2, changePercent: -0.28, pe: 8.2, marketCap: "₹1.2L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "10.4x", industryAvg: "16.8x", status: "undervalued" },
      { label: "P/B Ratio", value: "1.6x", industryAvg: "2.1x", status: "undervalued" },
      { label: "ROE", value: "18.2%", industryAvg: "15.2%", status: "undervalued" },
      { label: "Dividend Yield", value: "1.85%", industryAvg: "0.9%", status: "undervalued" },
    ],
    news: [
      { id: "1", title: "SBI reports record quarterly profit of ₹18,420 Cr", source: "Business Standard", timestamp: "1 day ago", summary: "Asset quality improves with GNPA ratio falling to 2.04%." },
    ],
    notes: [],
  },
  LT: {
    symbol: "LT",
    name: "Larsen & Toubro Ltd",
    price: 3642.8,
    change: 48.3,
    changePercent: 1.34,
    marketCap: "₹5.0L Cr",
    sector: "Infrastructure",
    industry: "Engineering & Construction",
    description:
      "L&T is India's largest engineering and construction conglomerate with businesses spanning infrastructure, hydrocarbon, power, defense, and technology services.",
    website: "larsentoubro.com",
    founded: "1938",
    employees: "50,000+",
    financials: {
      revenue: "₹2.55L Cr",
      revenueGrowth: 15.8,
      netProfit: "₹15,102 Cr",
      netProfitGrowth: 22.4,
      roe: 14.2,
      roce: 16.8,
      pe: 33.2,
      pb: 4.8,
      debtToEquity: 0.62,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹72,480 Cr", netProfit: "₹4,520 Cr", eps: 32.4, margin: 6.2 },
      { quarter: "Q3 FY25", revenue: "₹68,920 Cr", netProfit: "₹4,180 Cr", eps: 30.0, margin: 6.1 },
      { quarter: "Q2 FY25", revenue: "₹64,580 Cr", netProfit: "₹3,620 Cr", eps: 26.0, margin: 5.6 },
      { quarter: "Q1 FY25", revenue: "₹49,520 Cr", netProfit: "₹2,782 Cr", eps: 19.9, margin: 5.6 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹2.55L Cr", netProfit: "₹15,102 Cr", eps: 108.3, roe: 14.2 },
      { year: "FY24", revenue: "₹2.20L Cr", netProfit: "₹12,338 Cr", eps: 88.5, roe: 12.8 },
      { year: "FY23", revenue: "₹1.83L Cr", netProfit: "₹10,442 Cr", eps: 74.9, roe: 11.5 },
    ],
    shareholding: { promoter: 23.54, fii: 22.18, dii: 32.45, public: 21.83, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "ADANIENT", name: "Adani Enterprises", price: 2845.2, changePercent: 2.24, pe: 85.2, marketCap: "₹3.2L Cr" },
      { symbol: "NCC", name: "NCC Ltd", price: 268.4, changePercent: 0.82, pe: 18.4, marketCap: "₹0.2L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "33.2x", industryAvg: "28.0x", status: "overvalued" },
      { label: "P/B Ratio", value: "4.8x", industryAvg: "3.5x", status: "overvalued" },
      { label: "Order Book/PAT", value: "3.2x", industryAvg: "2.8x", status: "fair" },
      { label: "Dividend Yield", value: "0.92%", industryAvg: "1.0%", status: "fair" },
    ],
    news: [
      { id: "1", title: "L&T wins ₹12,500 Cr metro rail contract in Mumbai", source: "Economic Times", timestamp: "5 hours ago", summary: "Order book crosses ₹5.1L Cr with strong domestic infrastructure pipeline." },
    ],
    notes: [],
  },
  WIPRO: {
    symbol: "WIPRO",
    name: "Wipro Ltd",
    price: 285.6,
    change: -2.15,
    changePercent: -0.75,
    marketCap: "₹1.5L Cr",
    sector: "IT",
    industry: "IT Services & Consulting",
    description:
      "Wipro is a leading global information technology, consulting and business process services company delivering solutions across cloud, AI, and digital transformation.",
    website: "wipro.com",
    founded: "1945",
    employees: "2,35,000+",
    financials: {
      revenue: "₹89,760 Cr",
      revenueGrowth: 2.4,
      netProfit: "₹12,482 Cr",
      netProfitGrowth: 4.2,
      roe: 16.2,
      roce: 18.4,
      pe: 22.1,
      pb: 3.2,
      debtToEquity: 0.12,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹22,480 Cr", netProfit: "₹3,280 Cr", eps: 2.98, margin: 14.6 },
      { quarter: "Q3 FY25", revenue: "₹22,120 Cr", netProfit: "₹3,180 Cr", eps: 2.89, margin: 14.4 },
      { quarter: "Q2 FY25", revenue: "₹22,580 Cr", netProfit: "₹3,012 Cr", eps: 2.74, margin: 13.3 },
      { quarter: "Q1 FY25", revenue: "₹22,580 Cr", netProfit: "₹3,010 Cr", eps: 2.73, margin: 13.3 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹89,760 Cr", netProfit: "₹12,482 Cr", eps: 11.34, roe: 16.2 },
      { year: "FY24", revenue: "₹87,592 Cr", netProfit: "₹11,978 Cr", eps: 10.88, roe: 15.8 },
      { year: "FY23", revenue: "₹89,130 Cr", netProfit: "₹11,145 Cr", eps: 10.12, roe: 15.2 },
    ],
    shareholding: { promoter: 72.96, fii: 6.82, dii: 12.45, public: 7.77, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "INFY", name: "Infosys", price: 1892.15, changePercent: 1.56, pe: 28.4, marketCap: "₹7.8L Cr" },
      { symbol: "TCS", name: "Tata Consultancy Services", price: 4125.8, changePercent: 0.85, pe: 32.1, marketCap: "₹15.0L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "22.1x", industryAvg: "28.5x", status: "undervalued" },
      { label: "P/B Ratio", value: "3.2x", industryAvg: "7.2x", status: "undervalued" },
      { label: "EV/EBITDA", value: "15.2x", industryAvg: "20.1x", status: "undervalued" },
      { label: "Dividend Yield", value: "0.45%", industryAvg: "1.8%", status: "fair" },
    ],
    news: [
      { id: "1", title: "Wipro launches AI-powered consulting platform", source: "Mint", timestamp: "1 day ago", summary: "New platform targets $500M revenue opportunity over 3 years." },
    ],
    notes: [],
  },
  ADANIENT: {
    symbol: "ADANIENT",
    name: "Adani Enterprises Ltd",
    price: 2845.2,
    change: 62.4,
    changePercent: 2.24,
    marketCap: "₹3.2L Cr",
    sector: "Conglomerate",
    industry: "Diversified",
    description:
      "Adani Enterprises is the flagship company of the Adani Group, with businesses in energy, resources, logistics, agribusiness, and financial services.",
    website: "adani.com",
    founded: "1988",
    employees: "23,000+",
    financials: {
      revenue: "₹98,420 Cr",
      revenueGrowth: 28.4,
      netProfit: "₹3,512 Cr",
      netProfitGrowth: 42.8,
      roe: 8.2,
      roce: 9.4,
      pe: 85.2,
      pb: 6.8,
      debtToEquity: 1.24,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹28,420 Cr", netProfit: "₹1,120 Cr", eps: 9.8, margin: 3.9 },
      { quarter: "Q3 FY25", revenue: "₹26,180 Cr", netProfit: "₹980 Cr", eps: 8.6, margin: 3.7 },
      { quarter: "Q2 FY25", revenue: "₹24,520 Cr", netProfit: "₹820 Cr", eps: 7.2, margin: 3.3 },
      { quarter: "Q1 FY25", revenue: "₹19,300 Cr", netProfit: "₹592 Cr", eps: 5.2, margin: 3.1 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹98,420 Cr", netProfit: "₹3,512 Cr", eps: 30.8, roe: 8.2 },
      { year: "FY24", revenue: "₹76,620 Cr", netProfit: "₹2,458 Cr", eps: 21.6, roe: 6.4 },
      { year: "FY23", revenue: "₹58,420 Cr", netProfit: "₹1,842 Cr", eps: 16.2, roe: 5.8 },
    ],
    shareholding: { promoter: 72.28, fii: 10.42, dii: 8.85, public: 8.45, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "RELIANCE", name: "Reliance Industries", price: 2890.5, changePercent: 1.24, pe: 27.4, marketCap: "₹19.5L Cr" },
      { symbol: "LT", name: "Larsen & Toubro", price: 3642.8, changePercent: 1.34, pe: 33.2, marketCap: "₹5.0L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "85.2x", industryAvg: "22.1x", status: "overvalued" },
      { label: "P/B Ratio", value: "6.8x", industryAvg: "1.8x", status: "overvalued" },
      { label: "Revenue Growth", value: "28.4%", industryAvg: "11.2%", status: "undervalued" },
      { label: "Dividend Yield", value: "0.05%", industryAvg: "1.2%", status: "fair" },
    ],
    news: [
      { id: "1", title: "Adani Enterprises secures ₹8,200 Cr green hydrogen project", source: "Reuters", timestamp: "3 hours ago", summary: "New energy vertical gains traction with government PLI incentives." },
    ],
    notes: [],
  },
  MARUTI: {
    symbol: "MARUTI",
    name: "Maruti Suzuki India Ltd",
    price: 12450.0,
    change: 185.5,
    changePercent: 1.51,
    marketCap: "₹3.9L Cr",
    sector: "Auto",
    industry: "Passenger Vehicles",
    description:
      "Maruti Suzuki is India's largest passenger vehicle manufacturer with a market share exceeding 40%. It offers a wide range of cars from entry-level hatchbacks to premium SUVs.",
    website: "marutisuzuki.com",
    founded: "1981",
    employees: "18,000+",
    financials: {
      revenue: "₹1.48L Cr",
      revenueGrowth: 14.2,
      netProfit: "₹13,618 Cr",
      netProfitGrowth: 18.6,
      roe: 16.8,
      roce: 22.4,
      pe: 28.6,
      pb: 4.2,
      debtToEquity: 0.02,
    },
    
    quarterlyResults: [
      { quarter: "Q4 FY25", revenue: "₹39,820 Cr", netProfit: "₹3,820 Cr", eps: 122.4, margin: 9.6 },
      { quarter: "Q3 FY25", revenue: "₹38,420 Cr", netProfit: "₹3,520 Cr", eps: 112.8, margin: 9.2 },
      { quarter: "Q2 FY25", revenue: "₹36,180 Cr", netProfit: "₹3,280 Cr", eps: 105.1, margin: 9.1 },
      { quarter: "Q1 FY25", revenue: "₹33,580 Cr", netProfit: "₹2,998 Cr", eps: 96.1, margin: 8.9 },
    ],
    annualFinancials: [
      { year: "FY25", revenue: "₹1.48L Cr", netProfit: "₹13,618 Cr", eps: 436.4, roe: 16.8 },
      { year: "FY24", revenue: "₹1.30L Cr", netProfit: "₹11,482 Cr", eps: 368.0, roe: 15.2 },
      { year: "FY23", revenue: "₹1.12L Cr", netProfit: "₹8,049 Cr", eps: 257.8, roe: 12.4 },
    ],
    shareholding: { promoter: 56.21, fii: 22.45, dii: 14.82, public: 6.52, lastUpdated: "Mar 2026" },
    peers: [
      { symbol: "TATAMOTORS", name: "Tata Motors", price: 782.4, changePercent: 0.92, pe: 12.4, marketCap: "₹3.4L Cr" },
      { symbol: "M&M", name: "Mahindra & Mahindra", price: 3124.5, changePercent: 1.82, pe: 28.2, marketCap: "₹3.9L Cr" },
    ],
    valuation: [
      { label: "P/E Ratio", value: "28.6x", industryAvg: "24.0x", status: "overvalued" },
      { label: "P/B Ratio", value: "4.2x", industryAvg: "3.8x", status: "fair" },
      { label: "Market Share", value: "41.2%", industryAvg: "15.0%", status: "undervalued" },
      { label: "Dividend Yield", value: "0.82%", industryAvg: "1.0%", status: "fair" },
    ],
    news: [
      { id: "1", title: "Maruti Suzuki records highest-ever monthly sales", source: "Economic Times", timestamp: "4 hours ago", summary: "SUV portfolio drives 18% volume growth in June 2026." },
    ],
    notes: [],
  },
};

export function getMockSeed(symbol: string): Omit<CompanyProfile, "priceHistory"> | null {
  return MOCK_COMPANY_SEEDS[symbol.toUpperCase()] ?? null;
}

export function listMockSymbols(): string[] {
  return Object.keys(MOCK_COMPANY_SEEDS);
}
