import { applyCategoryDeduplication } from "@/lib/opportunity-engine/deduplication";
import {
  buildBestCalls,
  buildIntradayOpportunities,
  flattenRankedPool,
} from "@/lib/opportunity-engine/ranking";
import type {
  OpportunityCandidate,
  OpportunityEngineState,
  OpportunityRecommendationRecord,
  RecommendationRecordStatus,
} from "@/lib/opportunity-engine/types";
import { generateRecommendationId } from "@/src/core/recommendations/RecommendationIdentity";

function cloneCandidate(candidate: OpportunityCandidate): OpportunityCandidate {
  return JSON.parse(JSON.stringify(candidate)) as OpportunityCandidate;
}

function activeCandidatesFromEngine(
  state: OpportunityEngineState
): OpportunityCandidate[] {
  const deduped = applyCategoryDeduplication(state);
  const pool = flattenRankedPool(deduped);
  return pool.length === 0
    ? []
    : buildBestCalls(pool, buildIntradayOpportunities(deduped));
}

function createRecord(
  candidate: OpportunityCandidate,
  generatedAt: string
): OpportunityRecommendationRecord {
  const snapshot = cloneCandidate({ ...candidate, status: "ACTIVE" });
  return {
    recommendationId: generateRecommendationId({
      symbol: candidate.symbol,
      engine: candidate.category,
      generatedAt,
    }),
    candidate: snapshot,
    generatedAt,
    status: "ACTIVE",
    statusChangedAt: generatedAt,
    lifecycleEvents: [
      {
        status: "ACTIVE",
        occurredAt: generatedAt,
        reason: "Generated by AI recommendation engine",
      },
    ],
  };
}

function withStatus(
  record: OpportunityRecommendationRecord,
  status: RecommendationRecordStatus,
  occurredAt: string,
  reason: string
): OpportunityRecommendationRecord {
  if (record.status === status) return record;
  return {
    ...record,
    status,
    statusChangedAt: occurredAt,
    lifecycleEvents: [
      ...record.lifecycleEvents,
      { status, occurredAt, reason },
    ],
  };
}

/**
 * Reconciles the latest generated set with permanent recommendation memory.
 * Missing active recommendations expire; no record is removed or overwritten.
 */
export function syncRecommendationMemory(
  state: OpportunityEngineState,
  occurredAt = new Date().toISOString()
): OpportunityRecommendationRecord[] {
  const current = activeCandidatesFromEngine(state);
  const currentKeys = new Set(current.map((candidate) => candidate.id));
  const activeByCandidate = new Map(
    state.recommendations
      .filter((record) => record.status === "ACTIVE")
      .map((record) => [record.candidate.id, record])
  );
  const terminalSetupKeys = new Set(
    state.recommendations
      .filter(
        (record) =>
          record.status === "INVALIDATED" || record.status === "ARCHIVED"
      )
      .map(
        (record) =>
          `${record.candidate.id}:${record.candidate.firstDetectedAt}`
      )
  );

  const retained = state.recommendations.map((record) =>
    record.status === "ACTIVE" && !currentKeys.has(record.candidate.id)
      ? withStatus(
          record,
          "EXPIRED",
          occurredAt,
          "Setup no longer qualifies for the active recommendation set"
        )
      : record
  );

  for (const candidate of current) {
    const setupKey = `${candidate.id}:${candidate.firstDetectedAt}`;
    if (
      !activeByCandidate.has(candidate.id) &&
      !terminalSetupKeys.has(setupKey)
    ) {
      retained.push(createRecord(candidate, occurredAt));
    }
  }

  return retained;
}

export function listRecommendationHistory(
  state: Pick<OpportunityEngineState, "recommendations">,
  status?: RecommendationRecordStatus
): OpportunityRecommendationRecord[] {
  return state.recommendations
    .filter((record) => !status || record.status === status)
    .slice()
    .sort(
      (left, right) =>
        Date.parse(right.generatedAt) - Date.parse(left.generatedAt) ||
        right.recommendationId.localeCompare(left.recommendationId)
    );
}

export function listActiveRecommendationCandidates(
  state: Pick<OpportunityEngineState, "recommendations">
): OpportunityCandidate[] {
  return listRecommendationHistory(state, "ACTIVE").map((record) => ({
    ...record.candidate,
    status: "ACTIVE",
  }));
}

/**
 * Lifecycle transition without snapshot mutation. Archiving an active record
 * records the required ACTIVE -> EXPIRED -> ARCHIVED sequence.
 */
export function transitionRecommendation(
  records: readonly OpportunityRecommendationRecord[],
  recommendationId: string,
  status: Exclude<RecommendationRecordStatus, "ACTIVE">,
  reason: string,
  occurredAt = new Date().toISOString()
): OpportunityRecommendationRecord[] {
  return records.map((record) => {
    if (record.recommendationId !== recommendationId) return record;
    if (record.status === "ARCHIVED") return record;

    let next = record;
    if (status === "ARCHIVED" && next.status === "ACTIVE") {
      next = withStatus(
        next,
        "EXPIRED",
        occurredAt,
        "Expired before archival"
      );
    }
    return withStatus(next, status, occurredAt, reason);
  });
}

export function replayRecommendation(
  state: Pick<OpportunityEngineState, "recommendations">,
  recommendationId: string
): OpportunityRecommendationRecord | undefined {
  return state.recommendations.find(
    (record) => record.recommendationId === recommendationId
  );
}
