/**
 * Corporate actions repository (Sprint 10D.2).
 * Dividend, bonus, split, buyback, rights, AGM/EGM, listing, merger, open offer.
 */

import type { EventIntelligenceEvent } from "@/types/event";
import { addDays } from "@/src/core/events/EventFilters";
import {
  resolveEventStatus,
  stamp,
  tz,
} from "@/src/core/events/repositories/repoUtils";

export function listCorporateActionEvents(
  today: string
): EventIntelligenceEvent[] {
  const d = (offset: number) => addDays(today, offset);

  return [
    {
      id: "ca-hdfc-div",
      title: "HDFC Bank Interim Dividend",
      company: "HDFC Bank",
      ticker: "HDFCBANK",
      sector: "Financials",
      industry: "Private Banks",
      exchange: "NSE",
      eventType: "dividend",
      date: d(3),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(3), today),
      importance: "medium",
      description: "Board considered interim dividend for shareholders.",
      expectedImpact: "Income event",
      marketDirection: "neutral",
      affectedStocks: ["HDFCBANK"],
      affectedSectors: ["Financials"],
      historicalAvailable: true,
      tags: ["dividend", "banks"],
      marketCap: "mega",
      corporateActionDetail: {
        kind: "dividend",
        amountPerShare: 7.5,
        yieldPct: 0.42,
        exDate: d(3),
        recordDate: d(4),
        paymentDate: d(18),
        frequency: "interim",
      },
      ...stamp(d(-5)),
    },
    {
      id: "ca-itc-div",
      title: "ITC Final Dividend",
      company: "ITC",
      ticker: "ITC",
      sector: "Consumer Staples",
      industry: "Diversified",
      exchange: "NSE",
      eventType: "dividend",
      date: d(9),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(9), today),
      importance: "high",
      description: "High-yield final dividend declaration.",
      expectedImpact: "Income + ownership rebalance",
      marketDirection: "neutral",
      affectedStocks: ["ITC"],
      affectedSectors: ["Consumer Staples"],
      historicalAvailable: true,
      tags: ["dividend", "high-yield"],
      marketCap: "mega",
      corporateActionDetail: {
        kind: "dividend",
        amountPerShare: 14.75,
        yieldPct: 3.1,
        exDate: d(9),
        recordDate: d(10),
        paymentDate: d(24),
        frequency: "final",
      },
      ...stamp(d(-7)),
    },
    {
      id: "ca-wipro-bonus",
      title: "Wipro Bonus Issue Record Date",
      company: "Wipro",
      ticker: "WIPRO",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "bonus",
      date: d(10),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(10), today),
      importance: "medium",
      description: "Record date for approved bonus share issue.",
      expectedImpact: "Technical price adjustment",
      marketDirection: "neutral",
      affectedStocks: ["WIPRO"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["bonus", "it"],
      marketCap: "large",
      corporateActionDetail: {
        kind: "bonus",
        ratio: "1:1",
        effectiveDate: d(12),
      },
      ...stamp(d(-8)),
    },
    {
      id: "ca-maruti-split",
      title: "Maruti Suzuki Stock Split",
      company: "Maruti Suzuki",
      ticker: "MARUTI",
      sector: "Consumer Discretionary",
      industry: "Automobiles",
      exchange: "NSE",
      eventType: "stock_split",
      date: d(14),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(14), today),
      importance: "medium",
      description: "Ex-date for approved equity stock split.",
      expectedImpact: "Liquidity improvement",
      marketDirection: "neutral",
      affectedStocks: ["MARUTI"],
      affectedSectors: ["Automobiles"],
      historicalAvailable: false,
      tags: ["split", "auto"],
      marketCap: "large",
      corporateActionDetail: {
        kind: "stock_split",
        ratio: "5:1",
        faceValueBefore: 5,
        faceValueAfter: 1,
        effectiveDate: d(14),
      },
      ...stamp(d(-10)),
    },
    {
      id: "ca-infy-buyback",
      title: "Infosys Buyback Window",
      company: "Infosys",
      ticker: "INFY",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "buyback",
      date: d(5),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(5), today),
      importance: "high",
      description: "Share buyback programme open for tender.",
      expectedImpact: "Supportive near offer price",
      marketDirection: "bullish",
      affectedStocks: ["INFY"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: true,
      tags: ["buyback", "it"],
      marketCap: "mega",
      corporateActionDetail: {
        kind: "buyback",
        pricePerShare: 1850,
        offerSizeCr: 9800,
        recordDate: d(1),
        openDate: d(5),
        closeDate: d(19),
      },
      ...stamp(d(-6)),
    },
    {
      id: "ca-aether-rights",
      title: "Aether Industries Rights Issue",
      company: "Aether Industries",
      ticker: "AETHER",
      sector: "Materials",
      industry: "Specialty Chemicals",
      exchange: "NSE",
      eventType: "rights_issue",
      date: d(15),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(15), today),
      importance: "medium",
      description: "Rights issue opens for eligible shareholders.",
      expectedImpact: "Dilution and capital raise",
      marketDirection: "mixed",
      affectedStocks: ["AETHER"],
      affectedSectors: ["Materials"],
      historicalAvailable: false,
      tags: ["rights", "chemicals"],
      marketCap: "small",
      corporateActionDetail: {
        kind: "rights_issue",
        ratio: "1:8",
        issuePrice: 720,
        closingDate: d(29),
      },
      ...stamp(d(-11)),
    },
    {
      id: "ca-reliance-agm",
      title: "Reliance Industries AGM",
      company: "Reliance Industries",
      ticker: "RELIANCE",
      sector: "Energy",
      industry: "Oil & Gas",
      exchange: "NSE",
      eventType: "agm",
      date: d(4),
      time: "14:00",
      timezone: tz(),
      status: resolveEventStatus(d(4), today),
      importance: "medium",
      description: "Annual General Meeting of shareholders.",
      expectedImpact: null,
      marketDirection: "neutral",
      affectedStocks: ["RELIANCE"],
      affectedSectors: ["Energy", "Telecom", "Retail"],
      historicalAvailable: false,
      tags: ["agm", "governance"],
      marketCap: "mega",
      corporateActionDetail: {
        kind: "agm",
        venue: "Virtual / Mumbai",
        agenda: ["Adoption of accounts", "Dividend confirmation", "Director appointments"],
      },
      ...stamp(d(-3)),
    },
    {
      id: "ca-nova-listing",
      title: "NovaTech Exchange Listing",
      company: "NovaTech Systems",
      ticker: "NOVATECH",
      sector: "Information Technology",
      industry: "Software Products",
      exchange: "NSE",
      eventType: "listing",
      date: d(18),
      time: "09:15",
      timezone: tz(),
      status: resolveEventStatus(d(18), today),
      importance: "high",
      description: "Expected listing date subject to exchange confirmation.",
      expectedImpact: "Debut price discovery",
      marketDirection: "unknown",
      affectedStocks: ["NOVATECH"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["listing", "ipo"],
      marketCap: "mid",
      corporateActionDetail: {
        kind: "listing",
        exchangeNote: "NSE mainboard",
        effectiveDate: d(18),
      },
      ...stamp(d(-4)),
    },
    {
      id: "ca-nova-ipo",
      title: "NovaTech IPO Opens",
      company: "NovaTech Systems",
      ticker: "NOVATECH",
      sector: "Information Technology",
      industry: "Software Products",
      exchange: "NSE",
      eventType: "ipo",
      date: d(7),
      time: "10:00",
      timezone: tz(),
      status: resolveEventStatus(d(7), today),
      importance: "high",
      description: "IPO subscription window opens for retail and QIBs.",
      expectedImpact: "Primary market liquidity event",
      marketDirection: "bullish",
      affectedStocks: ["NOVATECH"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["ipo", "primary"],
      marketCap: "mid",
      corporateActionDetail: {
        kind: "listing",
        exchangeNote: "IPO open — listing expected later",
        effectiveDate: d(18),
      },
      ...stamp(d(-4)),
    },
    {
      id: "ca-merger-demo",
      title: "ChemCo – PolyChem Merger Effective",
      company: "ChemCo India",
      ticker: "CHEMCO",
      sector: "Materials",
      industry: "Chemicals",
      exchange: "NSE",
      eventType: "merger",
      date: d(16),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(16), today),
      importance: "high",
      description: "Scheme of amalgamation becomes effective.",
      expectedImpact: "Share swap and index float change",
      marketDirection: "mixed",
      affectedStocks: ["CHEMCO", "POLYCHEM"],
      affectedSectors: ["Materials"],
      historicalAvailable: false,
      tags: ["merger"],
      marketCap: "mid",
      corporateActionDetail: {
        kind: "merger",
        counterparty: "PolyChem Ltd",
        swapRatio: "3:2",
        effectiveDate: d(16),
      },
      ...stamp(d(-9)),
    },
    {
      id: "ca-open-offer",
      title: "Open Offer – Bharat Auto Components",
      company: "Bharat Auto Components",
      ticker: "BHARATAUTO",
      sector: "Consumer Discretionary",
      industry: "Auto Ancillaries",
      exchange: "BSE",
      eventType: "open_offer",
      date: d(12),
      time: null,
      timezone: tz(),
      status: resolveEventStatus(d(12), today),
      importance: "high",
      description: "Acquirer open offer to public shareholders.",
      expectedImpact: "Takeover premium dynamics",
      marketDirection: "bullish",
      affectedStocks: ["BHARATAUTO"],
      affectedSectors: ["Automobiles"],
      historicalAvailable: false,
      tags: ["open-offer", "mna"],
      marketCap: "small",
      corporateActionDetail: {
        kind: "open_offer",
        offerPrice: 465,
        offerSizePct: 26,
        openDate: d(12),
        closeDate: d(26),
      },
      ...stamp(d(-8)),
    },
  ];
}

export const corporateActionRepository = {
  list: listCorporateActionEvents,
  getById(today: string, id: string): EventIntelligenceEvent | null {
    return listCorporateActionEvents(today).find((e) => e.id === id) ?? null;
  },
};
