/**
 * Earnings & conference-call repository (Sprint 10D.2).
 * Structured NSE/BSE sample catalog — not hardcoded in UI components.
 */

import type { EventIntelligenceEvent } from "@/types/event";
import type { EarningsDetail } from "@/types/earnings";
import { addDays } from "@/src/core/events/EventFilters";
import {
  buildQuarterHistory,
  resolveEventStatus,
  stamp,
  tz,
} from "@/src/core/events/repositories/repoUtils";

function earningsDetail(
  quarter: EarningsDetail["quarter"],
  financialYear: string,
  announcementDate: string,
  announcementTime: string | null,
  seed: number,
  conferenceCallId: string | null
): EarningsDetail {
  const historical = buildQuarterHistory(`${quarter}-${financialYear}`, seed);
  const last = historical.quarters[historical.quarters.length - 1];
  return {
    quarter,
    financialYear,
    announcementDate,
    announcementTime,
    conferenceCallId,
    estimates: {
      expectedRevenueCr: Math.round(9200 + seed * 520),
      expectedEps: Number((22 + seed * 1.1).toFixed(2)),
      expectedYoyGrowthPct: Number((8 + (seed % 7) * 1.4).toFixed(1)),
      expectedQoqGrowthPct: Number((1.5 + (seed % 5) * 0.6).toFixed(1)),
      previousRevenueCr: last?.revenueCr ?? null,
      previousEps: last?.eps ?? null,
      previousQuarterLabel: last?.label ?? null,
      previousYearSameQuarterLabel: `${quarter} ${financialYear.replace(/\d{2}$/, (y) => String(Number(y) - 1))}`,
      historicalSurprisePct: historical.averageSurprisePct,
      managementGuidance:
        seed % 2 === 0
          ? "Management guided for mid-to-high single-digit revenue growth."
          : null,
      consensusRating:
        seed % 3 === 0 ? "Buy" : seed % 3 === 1 ? "Hold" : "Outperform",
    },
    historical,
  };
}

/** Earnings calendar + conference calls relative to `today`. */
export function listEarningsEvents(today: string): EventIntelligenceEvent[] {
  const d = (offset: number) => addDays(today, offset);

  const rows: EventIntelligenceEvent[] = [
    {
      id: "earn-tcs-q1",
      title: "TCS Q1 FY27 Results",
      company: "Tata Consultancy Services",
      ticker: "TCS",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(0),
      time: "16:30",
      timezone: tz(),
      status: resolveEventStatus(d(0), today, { live: true }),
      importance: "high",
      description:
        "First quarter financial results with revenue, margin and deal pipeline update.",
      expectedImpact: "IT sector sentiment driver",
      marketDirection: "unknown",
      affectedStocks: ["TCS", "INFY", "WIPRO"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: true,
      tags: ["earnings", "it", "nifty50"],
      marketCap: "mega",
      earningsDetail: earningsDetail("Q1", "FY27", d(0), "16:30", 3, "call-tcs-q1"),
      ...stamp(d(-2)),
    },
    {
      id: "call-tcs-q1",
      title: "TCS Earnings Conference Call",
      company: "Tata Consultancy Services",
      ticker: "TCS",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "conference_call",
      date: d(1),
      time: "18:00",
      timezone: tz(),
      status: resolveEventStatus(d(1), today),
      importance: "medium",
      description: "Post-results analyst conference call.",
      expectedImpact: null,
      marketDirection: "neutral",
      affectedStocks: ["TCS"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["call", "earnings"],
      marketCap: "mega",
      conferenceCallDetail: {
        hostCompany: "Tata Consultancy Services",
        hostTicker: "TCS",
        dialIn: "+91-22-6280-1141",
        webcastUrl: "https://www.tcs.com/investors",
        relatedEarningsId: "earn-tcs-q1",
        topics: ["Demand outlook", "Margins", "Large deal TCV"],
      },
      ...stamp(d(-2)),
    },
    {
      id: "earn-infy-q1",
      title: "Infosys Q1 FY27 Results",
      company: "Infosys",
      ticker: "INFY",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(2),
      time: "16:00",
      timezone: tz(),
      status: resolveEventStatus(d(2), today),
      importance: "high",
      description: "Quarterly results with guidance commentary.",
      expectedImpact: "Large-cap IT cue",
      marketDirection: "unknown",
      affectedStocks: ["INFY", "TCS", "HCLTECH"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: true,
      tags: ["earnings", "it"],
      marketCap: "mega",
      earningsDetail: earningsDetail("Q1", "FY27", d(2), "16:00", 5, "call-infy-q1"),
      ...stamp(d(-3)),
    },
    {
      id: "call-infy-q1",
      title: "Infosys Conference Call",
      company: "Infosys",
      ticker: "INFY",
      sector: "Information Technology",
      industry: "IT Services",
      exchange: "NSE",
      eventType: "conference_call",
      date: d(2),
      time: "18:30",
      timezone: tz(),
      status: resolveEventStatus(d(2), today),
      importance: "medium",
      description: "Management Q&A with analysts.",
      expectedImpact: null,
      marketDirection: "neutral",
      affectedStocks: ["INFY"],
      affectedSectors: ["Information Technology"],
      historicalAvailable: false,
      tags: ["call"],
      marketCap: "mega",
      conferenceCallDetail: {
        hostCompany: "Infosys",
        hostTicker: "INFY",
        dialIn: "+91-22-6280-1349",
        webcastUrl: null,
        relatedEarningsId: "earn-infy-q1",
        topics: ["Guidance", "Attrition", "GenAI deals"],
      },
      ...stamp(d(-3)),
    },
    {
      id: "earn-sbin-q1",
      title: "SBI Q1 FY27 Results",
      company: "State Bank of India",
      ticker: "SBIN",
      sector: "Financials",
      industry: "Public Banks",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(-2),
      time: "14:00",
      timezone: tz(),
      status: resolveEventStatus(d(-2), today),
      importance: "high",
      description: "Quarterly results for India's largest PSU bank.",
      expectedImpact: "PSU bank complex cue",
      marketDirection: "unknown",
      affectedStocks: ["SBIN", "BANKBARODA", "PNB"],
      affectedSectors: ["Financials"],
      historicalAvailable: true,
      tags: ["earnings", "banks", "psu"],
      marketCap: "mega",
      earningsDetail: earningsDetail("Q1", "FY27", d(-2), "14:00", 7, null),
      ...stamp(d(-12)),
    },
    {
      id: "earn-reliance-q1",
      title: "Reliance Industries Q1 FY27 Results",
      company: "Reliance Industries",
      ticker: "RELIANCE",
      sector: "Energy",
      industry: "Oil & Gas",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(6),
      time: "17:00",
      timezone: tz(),
      status: resolveEventStatus(d(6), today),
      importance: "critical",
      description: "Conglomerate quarterly print across O2C, retail and Jio.",
      expectedImpact: "Index heavyweight move",
      marketDirection: "mixed",
      affectedStocks: ["RELIANCE"],
      affectedSectors: ["Energy", "Telecom", "Retail"],
      historicalAvailable: true,
      tags: ["earnings", "conglomerate"],
      marketCap: "mega",
      earningsDetail: earningsDetail("Q1", "FY27", d(6), "17:00", 9, null),
      ...stamp(d(-4)),
    },
    {
      id: "earn-hdfc-q1",
      title: "HDFC Bank Q1 FY27 Results",
      company: "HDFC Bank",
      ticker: "HDFCBANK",
      sector: "Financials",
      industry: "Private Banks",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(8),
      time: "15:30",
      timezone: tz(),
      status: resolveEventStatus(d(8), today),
      importance: "high",
      description: "Private bank quarterly results and NIMs commentary.",
      expectedImpact: "Banking sector cue",
      marketDirection: "unknown",
      affectedStocks: ["HDFCBANK", "ICICIBANK", "AXISBANK"],
      affectedSectors: ["Financials"],
      historicalAvailable: true,
      tags: ["earnings", "banks"],
      marketCap: "mega",
      earningsDetail: earningsDetail("Q1", "FY27", d(8), "15:30", 4, null),
      ...stamp(d(-5)),
    },
    {
      id: "earn-aether-q1",
      title: "Aether Industries Q1 FY27 Results",
      company: "Aether Industries",
      ticker: "AETHER",
      sector: "Materials",
      industry: "Specialty Chemicals",
      exchange: "NSE",
      eventType: "quarterly_results",
      date: d(11),
      time: "16:00",
      timezone: tz(),
      status: resolveEventStatus(d(11), today),
      importance: "medium",
      description: "Small-cap specialty chemical quarterly print.",
      expectedImpact: "Chemicals pocket cue",
      marketDirection: "unknown",
      affectedStocks: ["AETHER"],
      affectedSectors: ["Materials"],
      historicalAvailable: true,
      tags: ["earnings", "chemicals"],
      marketCap: "small",
      earningsDetail: earningsDetail("Q1", "FY27", d(11), "16:00", 2, null),
      ...stamp(d(-6)),
    },
  ];

  return rows;
}

export const earningsRepository = {
  list: listEarningsEvents,
  getById(today: string, id: string): EventIntelligenceEvent | null {
    return listEarningsEvents(today).find((e) => e.id === id) ?? null;
  },
};
