/**
 * Macro / economic event repository (Sprint 10D.2).
 */

import type { EventIntelligenceEvent } from "@/types/event";
import { addDays } from "@/src/core/events/EventFilters";
import {
  resolveEventStatus,
  stamp,
  tz,
} from "@/src/core/events/repositories/repoUtils";

export function listEconomicEvents(today: string): EventIntelligenceEvent[] {
  const d = (offset: number) => addDays(today, offset);

  return [
    {
      id: "macro-rbi",
      title: "RBI Monetary Policy Decision",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Monetary Policy",
      exchange: "MACRO",
      eventType: "rbi_policy",
      date: d(0),
      time: "10:00",
      timezone: tz(),
      status: resolveEventStatus(d(0), today),
      importance: "critical",
      description:
        "Reserve Bank of India MPC rate decision and policy statement.",
      expectedImpact: "High volatility across rates-sensitive sectors",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["Banks", "NBFCs", "Realty"],
      historicalAvailable: true,
      tags: ["rbi", "rates", "mpc"],
      marketCap: "unknown",
      ...stamp(d(0)),
    },
    {
      id: "macro-cpi",
      title: "India CPI Inflation Print",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Inflation",
      exchange: "MACRO",
      eventType: "cpi",
      date: d(3),
      time: "17:30",
      timezone: tz(),
      status: resolveEventStatus(d(3), today),
      importance: "high",
      description: "Monthly consumer price inflation release.",
      expectedImpact: "Rates and INR sensitivity",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["Banks", "FMCG", "Consumer Durables"],
      historicalAvailable: true,
      tags: ["cpi", "inflation", "macro"],
      marketCap: "unknown",
      ...stamp(d(-1)),
    },
    {
      id: "macro-fed",
      title: "FOMC Rate Decision",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Monetary Policy",
      exchange: "MACRO",
      eventType: "fed_meeting",
      date: d(6),
      time: "23:30",
      timezone: tz(),
      status: resolveEventStatus(d(6), today),
      importance: "critical",
      description:
        "US Federal Reserve interest rate decision and press conference.",
      expectedImpact: "Global risk assets and INR",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["IT", "Metals", "Banks"],
      historicalAvailable: true,
      tags: ["fed", "fomc", "global"],
      marketCap: "unknown",
      ...stamp(d(-2)),
    },
    {
      id: "macro-gdp",
      title: "India GDP Advance Estimates",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Growth",
      exchange: "MACRO",
      eventType: "gdp",
      date: d(13),
      time: "17:30",
      timezone: tz(),
      status: resolveEventStatus(d(13), today),
      importance: "high",
      description: "Quarterly GDP advance estimates from MoSPI.",
      expectedImpact: "Broad market sentiment",
      marketDirection: "unknown",
      affectedStocks: [],
      affectedSectors: ["All"],
      historicalAvailable: true,
      tags: ["gdp", "growth"],
      marketCap: "unknown",
      ...stamp(d(-1)),
    },
    {
      id: "macro-msci",
      title: "MSCI Semi-Annual Index Review",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Index Rebalance",
      exchange: "MACRO",
      eventType: "msci_review",
      date: d(17),
      time: "22:00",
      timezone: tz(),
      status: resolveEventStatus(d(17), today),
      importance: "critical",
      description: "MSCI announces inclusions, exclusions and weight changes.",
      expectedImpact: "Passive flow impact on reviewed names",
      marketDirection: "mixed",
      affectedStocks: [],
      affectedSectors: ["All"],
      historicalAvailable: true,
      tags: ["msci", "rebalance", "flows"],
      marketCap: "unknown",
      ...stamp(d(-8)),
    },
    {
      id: "macro-pmi",
      title: "India Manufacturing PMI",
      company: null,
      ticker: null,
      sector: "Macro",
      industry: "Manufacturing",
      exchange: "MACRO",
      eventType: "pmi",
      date: d(-1),
      time: "10:30",
      timezone: tz(),
      status: resolveEventStatus(d(-1), today),
      importance: "medium",
      description: "S&P Global India Manufacturing PMI.",
      expectedImpact: "Cyclical sector cue",
      marketDirection: "neutral",
      affectedStocks: [],
      affectedSectors: ["Industrials", "Metals"],
      historicalAvailable: true,
      tags: ["pmi", "manufacturing"],
      marketCap: "unknown",
      ...stamp(d(-5)),
    },
  ];
}

export const economicEventRepository = {
  list: listEconomicEvents,
};
