/**
 * Smart Watchlist Platform — domain models (Sprint 10B.R2).
 * Dynamic collections, rules, tags, grouping, recommendations.
 */

import { safeWatchlistNumber, safeWatchlistText } from "../WatchlistModels";

export const SMART_WATCHLIST_EMPTY = {
  noDynamicRules: "No Dynamic Rules",
  noSuggestions: "No Suggestions",
  noMatches: "No Matches",
  awaitingAiAnalysis: "Awaiting AI Analysis",
} as const;

export type SmartWatchlistEmptyMessage =
  (typeof SMART_WATCHLIST_EMPTY)[keyof typeof SMART_WATCHLIST_EMPTY];

export const DYNAMIC_WATCHLIST_TEMPLATES = [
  "top_conviction",
  "upcoming_earnings",
  "high_trust",
  "low_risk",
  "momentum",
  "value",
  "growth",
  "dividend",
  "turnaround",
  "fifty_two_week_high",
  "fifty_two_week_low",
] as const;

export type DynamicWatchlistTemplateId =
  (typeof DYNAMIC_WATCHLIST_TEMPLATES)[number];

export const DYNAMIC_TEMPLATE_LABELS: Record<DynamicWatchlistTemplateId, string> =
  {
    top_conviction: "Top Conviction",
    upcoming_earnings: "Upcoming Earnings",
    high_trust: "High Trust",
    low_risk: "Low Risk",
    momentum: "Momentum",
    value: "Value",
    growth: "Growth",
    dividend: "Dividend",
    turnaround: "Turnaround",
    fifty_two_week_high: "52 Week High",
    fifty_two_week_low: "52 Week Low",
  };

export const WATCHLIST_RULE_FIELDS = [
  "market_cap",
  "sector",
  "industry",
  "pe",
  "roe",
  "sales_growth",
  "profit_growth",
  "rs_rating",
  "momentum",
  "volume",
  "ai_conviction",
  "trust_score",
  "validation_score",
  "portfolio_status",
  "watchlist_status",
  "risk_score",
  "dividend_yield",
  "days_to_earnings",
  "near_52w_high",
  "near_52w_low",
] as const;

export type WatchlistRuleField = (typeof WATCHLIST_RULE_FIELDS)[number];

export const WATCHLIST_RULE_OPERATORS = [
  "gt",
  "lt",
  "gte",
  "lte",
  "eq",
  "contains",
  "between",
] as const;

export type WatchlistRuleOperator = (typeof WATCHLIST_RULE_OPERATORS)[number];

export const GROUPING_DIMENSIONS = [
  "sector",
  "industry",
  "theme",
  "market_cap",
  "risk",
  "conviction",
  "trust",
] as const;

export type GroupingDimension = (typeof GROUPING_DIMENSIONS)[number];

/** Candidate row — metric bag only, no recalculation. */
export interface SmartWatchlistCandidate {
  ticker: string;
  company?: string | null;
  sector?: string | null;
  industry?: string | null;
  theme?: string | null;
  metrics: Record<string, number | string | null | undefined>;
  inPortfolio?: boolean;
  inWatchlist?: boolean;
}

export interface WatchlistLeafRule {
  kind: "leaf";
  id: string;
  field: WatchlistRuleField | string;
  operator: WatchlistRuleOperator;
  value: number | string;
  valueTo?: number;
  label?: string;
}

export interface WatchlistRuleGroup {
  kind: "group";
  id: string;
  logic: "and" | "or" | "not";
  children: WatchlistRuleNode[];
  label?: string;
}

export type WatchlistRuleNode = WatchlistLeafRule | WatchlistRuleGroup;

export interface DynamicWatchlistDefinition {
  id: string;
  templateId: DynamicWatchlistTemplateId | "custom";
  name: string;
  description: string;
  root: WatchlistRuleGroup;
  tags: string[];
  priority: number;
  createdAt: string;
  updatedAt: string;
  empty: boolean;
  emptyMessage: SmartWatchlistEmptyMessage;
}

export interface DynamicWatchlistRunResult {
  watchlistId: string;
  templateId: string;
  matches: SmartWatchlistCandidate[];
  matchCount: number;
  rulesEvaluated: number;
  empty: boolean;
  emptyMessage: SmartWatchlistEmptyMessage;
  ranAt: string;
}

export interface CompanyTag {
  ticker: string;
  tags: string[];
  category: string;
  priority: number;
  autoGenerated: boolean;
}

export interface WatchlistGroupBucket {
  key: string;
  label: string;
  dimension: GroupingDimension;
  tickers: string[];
  count: number;
}

export interface WatchlistGroupingView {
  dimension: GroupingDimension;
  buckets: WatchlistGroupBucket[];
  total: number;
  empty: boolean;
  emptyMessage: SmartWatchlistEmptyMessage;
}

export interface WatchlistRecommendation {
  ticker: string;
  action: "add" | "remove" | "monitor" | "trending" | "ai_suggest";
  reason: string;
  score: number;
  priority: number;
}

export interface WatchlistRecommendationsView {
  toAdd: WatchlistRecommendation[];
  toRemove: WatchlistRecommendation[];
  toMonitor: WatchlistRecommendation[];
  trending: WatchlistRecommendation[];
  aiSuggestions: WatchlistRecommendation[];
  suggestedWatchlists: Array<{ templateId: string; label: string; reason: string }>;
  duplicates: Array<{ watchlistIds: string[]; overlap: string[] }>;
  empty: boolean;
  emptyMessage: SmartWatchlistEmptyMessage;
}

export interface SmartWatchlistView {
  dynamic: DynamicWatchlistDefinition[];
  lastRun: DynamicWatchlistRunResult | null;
  tags: CompanyTag[];
  grouping: WatchlistGroupingView | null;
  recommendations: WatchlistRecommendationsView;
  empty: boolean;
  emptyMessage: SmartWatchlistEmptyMessage;
}

export function safeSmartText(
  value: string | null | undefined,
  fallback: string
): string {
  return safeWatchlistText(value, fallback);
}

export function safeSmartNumber(
  value: number | null | undefined,
  fallback = 0
): number {
  return safeWatchlistNumber(value, fallback);
}

export function emptyDynamicWatchlist(
  message: SmartWatchlistEmptyMessage = SMART_WATCHLIST_EMPTY.noDynamicRules
): DynamicWatchlistDefinition {
  const now = new Date().toISOString();
  return {
    id: "",
    templateId: "custom",
    name: message,
    description: "",
    root: { kind: "group", id: "empty", logic: "and", children: [] },
    tags: [],
    priority: 0,
    createdAt: now,
    updatedAt: now,
    empty: true,
    emptyMessage: message,
  };
}

export function emptyRecommendationsView(
  message: SmartWatchlistEmptyMessage = SMART_WATCHLIST_EMPTY.noSuggestions
): WatchlistRecommendationsView {
  return {
    toAdd: [],
    toRemove: [],
    toMonitor: [],
    trending: [],
    aiSuggestions: [],
    suggestedWatchlists: [],
    duplicates: [],
    empty: true,
    emptyMessage: message,
  };
}

export function emptySmartWatchlistView(
  message: SmartWatchlistEmptyMessage = SMART_WATCHLIST_EMPTY.awaitingAiAnalysis
): SmartWatchlistView {
  return {
    dynamic: [],
    lastRun: null,
    tags: [],
    grouping: null,
    recommendations: emptyRecommendationsView(),
    empty: true,
    emptyMessage: message,
  };
}
