/**
 * Watchlist Tag Engine — AI organization tags (Sprint 10B.R2).
 */

import {
  SMART_WATCHLIST_EMPTY,
  safeSmartNumber,
  safeSmartText,
  type CompanyTag,
  type SmartWatchlistCandidate,
} from "./SmartWatchlistModels";

const tagCache = new Map<string, CompanyTag>();

function marketCapBand(value: number): string {
  if (value >= 100_000) return "large_cap";
  if (value >= 20_000) return "mid_cap";
  return "small_cap";
}

function autoCategory(candidate: SmartWatchlistCandidate): string {
  const sector = safeSmartText(candidate.sector, "");
  if (sector) return sector;
  const theme = safeSmartText(candidate.theme, "");
  if (theme) return theme;
  return "uncategorized";
}

function autoPriority(candidate: SmartWatchlistCandidate): number {
  const conviction = safeSmartNumber(
    candidate.metrics.ai_conviction as number | null,
    0
  );
  const trust = safeSmartNumber(
    candidate.metrics.trust_score as number | null,
    0
  );
  return Math.round(conviction * 0.6 + trust * 0.4);
}

function buildAutoTags(candidate: SmartWatchlistCandidate): string[] {
  const tags = new Set<string>();
  const sector = safeSmartText(candidate.sector, "");
  const industry = safeSmartText(candidate.industry, "");
  const theme = safeSmartText(candidate.theme, "");

  if (sector) tags.add(`sector:${sector.toLowerCase()}`);
  if (industry) tags.add(`industry:${industry.toLowerCase()}`);
  if (theme) tags.add(`theme:${theme.toLowerCase()}`);

  const conviction = safeSmartNumber(
    candidate.metrics.ai_conviction as number | null,
    0
  );
  const trust = safeSmartNumber(
    candidate.metrics.trust_score as number | null,
    0
  );
  const risk = safeSmartNumber(
    candidate.metrics.risk_score as number | null,
    100
  );
  const momentum = safeSmartNumber(
    candidate.metrics.momentum as number | null,
    0
  );

  if (conviction >= 75) tags.add("high_conviction");
  if (trust >= 70) tags.add("high_trust");
  if (risk <= 30) tags.add("low_risk");
  if (momentum >= 60) tags.add("momentum_leader");
  if (candidate.inPortfolio) tags.add("portfolio");
  if (candidate.inWatchlist) tags.add("watchlist");

  const mcap = safeSmartNumber(
    candidate.metrics.market_cap as number | null,
    0
  );
  if (mcap > 0) tags.add(marketCapBand(mcap));

  return Array.from(tags);
}

export function tagCompanies(
  candidates: readonly SmartWatchlistCandidate[]
): CompanyTag[] {
  const out: CompanyTag[] = [];
  for (const candidate of candidates) {
    const ticker = safeSmartText(candidate.ticker, "").toUpperCase();
    if (!ticker) continue;

    const tag: CompanyTag = {
      ticker,
      tags: buildAutoTags(candidate),
      category: autoCategory(candidate),
      priority: autoPriority(candidate),
      autoGenerated: true,
    };
    tagCache.set(ticker, tag);
    out.push(tag);
  }
  return out.sort((a, b) => b.priority - a.priority);
}

export function getCompanyTags(ticker: string): CompanyTag | null {
  return tagCache.get(safeSmartText(ticker, "").toUpperCase()) ?? null;
}

export function listTaggedCompanies(): CompanyTag[] {
  return Array.from(tagCache.values()).sort((a, b) => b.priority - a.priority);
}

export function detectDuplicateTags(
  candidates: readonly SmartWatchlistCandidate[]
): string[] {
  const seen = new Map<string, string>();
  const duplicates: string[] = [];
  for (const c of candidates) {
    const ticker = safeSmartText(c.ticker, "").toUpperCase();
    const key = `${c.sector ?? ""}|${c.industry ?? ""}|${autoCategory(c)}`;
    if (seen.has(key) && seen.get(key) !== ticker) {
      duplicates.push(ticker);
    } else {
      seen.set(key, ticker);
    }
  }
  return duplicates;
}

export function emptyTagsMessage(): string {
  return SMART_WATCHLIST_EMPTY.awaitingAiAnalysis;
}

export function resetWatchlistTags(): void {
  tagCache.clear();
}

export class WatchlistTagEngine {
  tagCompanies = tagCompanies;
  getCompanyTags = getCompanyTags;
  listTaggedCompanies = listTaggedCompanies;
  reset = resetWatchlistTags;
}
