/**
 * Institutional research report section templates.
 */

export const REPORT_SECTIONS = [
  "Executive Summary",
  "Business Overview",
  "Industry Structure",
  "Competitive Advantages (Moat)",
  "Management Quality",
  "Financial Performance",
  "Quarterly Analysis",
  "Annual Growth Analysis",
  "Cash Flow Analysis",
  "Balance Sheet Strength",
  "Shareholding Analysis",
  "Valuation",
  "Technical Trend",
  "Key Risks",
  "Key Catalysts",
  "Bull Case",
  "Bear Case",
  "Base Case",
  "Probability Matrix",
  "Final Verdict",
] as const;

export type ReportSectionKey = (typeof REPORT_SECTIONS)[number];

export interface ReportSection {
  key: ReportSectionKey;
  title: string;
  content: string;
}

export interface InstitutionalReportHeader {
  symbol: string;
  companyName: string;
  sector: string;
  industry: string;
  price: number;
  changePercent: number;
  marketCap: string;
  generatedAt: string;
  dataProvider: string;
}

export function sectionHeading(title: string): string {
  return `## ${title}`;
}

export function bulletList(items: string[]): string {
  if (items.length === 0) return "_No data available._";
  return items.map((item) => `- ${item}`).join("\n");
}

export function scoreLine(label: string, score: number, max = 10): string {
  return `| ${label} | ${score.toFixed(1)} / ${max} |`;
}

export function renderReportMarkdown(
  header: InstitutionalReportHeader,
  sections: ReportSection[],
  ratingTable: string,
  probabilityMatrix: string,
  decisionSummary?: string
): string {
  const meta = [
    `# Institutional Research Report`,
    ``,
    `**${header.companyName} (${header.symbol})**`,
    ``,
    `| Field | Value |`,
    `| --- | --- |`,
    `| Sector | ${header.sector} |`,
    `| Industry | ${header.industry} |`,
    `| Price | ₹${header.price.toLocaleString("en-IN")} (${header.changePercent > 0 ? "+" : ""}${header.changePercent.toFixed(2)}%) |`,
    `| Market Cap | ${header.marketCap} |`,
    `| Generated | ${header.generatedAt} |`,
    `| Data Source | ${header.dataProvider} |`,
    ``,
    `---`,
    ``,
    `### Rating Summary`,
    ``,
    ratingTable,
    ``,
    `---`,
    ``,
  ].join("\n");

  const body = sections
    .map((section) => `${sectionHeading(section.title)}\n\n${section.content}`)
    .join("\n\n");

  const footer = [
    ``,
    `---`,
    ``,
    sectionHeading("Probability Matrix"),
    ``,
    probabilityMatrix,
    decisionSummary ?? "",
    ``,
    `*This institutional research report is AI-generated by EquityOS using live fundamentals, intelligence engines, and indexed filings. It is not investment advice.*`,
  ].join("\n");

  return `${meta}${body}${footer}`;
}

export function renderRatingTable(input: {
  overallRating: string;
  overallScore: number;
  businessQuality: number;
  financialStrength: number;
  valuation: number;
  growth: number;
  risk: number;
  management: number;
  technical: number;
}): string {
  return [
    `| Metric | Score |`,
    `| --- | --- |`,
    `| **Overall Score** | **${input.overallScore} / 100** |`,
    `| **Recommendation** | **${input.overallRating}** |`,
    scoreLine("Business Quality", input.businessQuality),
    scoreLine("Financial Strength", input.financialStrength),
    scoreLine("Valuation", input.valuation),
    scoreLine("Growth", input.growth),
    scoreLine("Risk (higher = safer)", input.risk),
    scoreLine("Management", input.management),
    scoreLine("Technical", input.technical),
  ].join("\n");
}

export function renderProbabilityMatrix(cases: {
  bull: number;
  base: number;
  bear: number;
}): string {
  const total = cases.bull + cases.base + cases.bear;
  return [
    `| Scenario | Probability |`,
    `| --- | --- |`,
    `| Bull Case | ${cases.bull}% |`,
    `| Base Case | ${cases.base}% |`,
    `| Bear Case | ${cases.bear}% |`,
    `| **Total** | **${total}%** |`,
  ].join("\n");
}

export function isInstitutionalAnalysisRequest(prompt: string): boolean {
  const trimmed = prompt.trim().toLowerCase();
  if (!trimmed) return false;

  const patterns = [
    /^(analyse|analyze|analysis of|research on|institutional report on|full report on)\b/,
    /^(give me |provide |generate )?(an |a )?(full )?(institutional )?(analysis|report) (of|on|for)\b/,
    /\banalyse\s+\S+/,
    /\banalyze\s+\S+/,
  ];

  return patterns.some((pattern) => pattern.test(trimmed));
}
