"use client";

import type { ReportViewerMetadata } from "@/lib/dashboard/institutional-report-viewer";

export function ReportMetadataPanel({
  metadata,
}: {
  metadata: ReportViewerMetadata;
}) {
  const rows: Array<{ label: string; value: string }> = [
    { label: "Generated By", value: metadata.generatedBy },
    { label: "Generated At", value: metadata.generatedAt },
    { label: "Report Version", value: metadata.reportVersion },
    { label: "Environment", value: metadata.environment },
    { label: "Execution ID", value: metadata.executionId },
    { label: "Snapshot ID", value: metadata.snapshotId },
    { label: "Platform Build", value: metadata.platformBuild },
    { label: "Report Type", value: metadata.reportType },
    { label: "Market Session", value: metadata.marketSession },
    { label: "Institutional Grade", value: metadata.institutionalGrade },
    { label: "Platform Version", value: metadata.platformVersion },
    { label: "Validation Version", value: metadata.validationVersion },
    { label: "Trust Version", value: metadata.trustVersion },
    { label: "AI Version", value: metadata.aiVersion },
  ];

  return (
    <div
      data-testid="report-metadata-panel"
      className="rounded-lg border border-surface-border-subtle/80 bg-surface-hover/10 px-3 py-3"
    >
      <p className="mb-2 text-[10px] font-medium uppercase tracking-wider text-text-faint">
        Report Metadata
      </p>
      <dl className="grid grid-cols-1 gap-x-4 gap-y-1.5 sm:grid-cols-2">
        {rows.map((row) => (
          <div key={row.label} className="flex justify-between gap-2 sm:block">
            <dt className="text-[9px] font-medium uppercase tracking-wider text-text-faint">
              {row.label}
            </dt>
            <dd className="text-[11px] font-medium text-text-primary">{row.value}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}
