/**
 * Institutional Report Export Center — configuration (Prompt 9F.R1).
 * Versions, watermarks, formats, and tier gates live here; no magic numbers elsewhere.
 */

export type ExportableFormat = "PDF" | "EXCEL" | "MARKDOWN" | "PRINT";

export type ExportEnvironment = "development" | "staging" | "production" | "test";

export type SubscriptionTier =
  | "none"
  | "basic"
  | "pro"
  | "enterprise";

export type ExportUserRole = "administrator" | "subscriber" | "free";

export interface ExportVersionInfo {
  aiVersion: string;
  validationVersion: string;
  trustVersion: string;
  platformVersion: string;
  reportVersion: string;
  exportEngineVersion: string;
}

export interface ExportConfiguration {
  engineVersion: string;
  environment: ExportEnvironment;
  watermark: string;
  defaultGeneratedBy: string;
  enabledFormats: ExportableFormat[];
  maxAuditEntries: number;
  maxExportHistory: number;
  versions: ExportVersionInfo;
  /** Subscription tiers that may download Excel. */
  excelAllowedTiers: SubscriptionTier[];
  disclaimer: string;
  institutionalMode: boolean;
}

export const DEFAULT_EXPORT_CONFIGURATION: ExportConfiguration = {
  engineVersion: "9F.R1.0",
  environment: "development",
  watermark: "EQUITYOS CONFIDENTIAL — INSTITUTIONAL USE ONLY",
  defaultGeneratedBy: "EquityOS Report Export Center",
  enabledFormats: ["PDF", "EXCEL", "MARKDOWN", "PRINT"],
  maxAuditEntries: 500,
  maxExportHistory: 200,
  versions: {
    aiVersion: "9F.AI.1",
    validationVersion: "9F.VAL.1",
    trustVersion: "9F.TRUST.1",
    platformVersion: "9F.32.0",
    reportVersion: "9F.15.0",
    exportEngineVersion: "9F.R1.0",
  },
  excelAllowedTiers: ["pro", "enterprise"],
  disclaimer:
    "This report is generated by EquityOS for institutional research and decision-support only. It does not constitute investment advice. Past validation performance does not guarantee future results. Redistribution without authorization is prohibited.",
  institutionalMode: true,
};

export type ExportConfigurationInput = Partial<
  Omit<ExportConfiguration, "versions" | "enabledFormats" | "excelAllowedTiers">
> & {
  versions?: Partial<ExportVersionInfo>;
  enabledFormats?: ExportableFormat[];
  excelAllowedTiers?: SubscriptionTier[];
};

export function resolveExportConfiguration(
  input?: ExportConfigurationInput
): ExportConfiguration {
  const base = DEFAULT_EXPORT_CONFIGURATION;
  return {
    ...base,
    ...input,
    enabledFormats: [
      ...(input?.enabledFormats ?? base.enabledFormats),
    ],
    excelAllowedTiers: [
      ...(input?.excelAllowedTiers ?? base.excelAllowedTiers),
    ],
    versions: {
      ...base.versions,
      ...input?.versions,
    },
    maxAuditEntries: Math.max(1, input?.maxAuditEntries ?? base.maxAuditEntries),
    maxExportHistory: Math.max(
      1,
      input?.maxExportHistory ?? base.maxExportHistory
    ),
  };
}
