/**
 * Shared export document model — professional institutional sections + metadata.
 */

import type { InstitutionalReport } from "../ReportBuilder";
import type { ExportConfiguration } from "./ExportConfiguration";

export interface ExportReportMetadata {
  generatedOn: string;
  generatedBy: string;
  aiVersion: string;
  validationVersion: string;
  trustVersion: string;
  platformVersion: string;
  reportVersion: string;
  environment: string;
  watermark: string;
  reportId: string;
  reportType: string;
}

export interface ExportDocumentSection {
  id: string;
  heading: string;
  paragraphs: string[];
  tables?: Array<{ headers: string[]; rows: string[][] }>;
  chartRefs?: Array<{ id: string; title: string; description: string }>;
}

export interface ExportDocument {
  title: string;
  subtitle: string;
  metadata: ExportReportMetadata;
  sections: ExportDocumentSection[];
  disclaimer: string;
}

export function buildExportMetadata(
  report: InstitutionalReport,
  config: ExportConfiguration,
  generatedBy?: string
): ExportReportMetadata {
  return {
    generatedOn: new Date().toISOString(),
    generatedBy: generatedBy ?? config.defaultGeneratedBy,
    aiVersion: config.versions.aiVersion,
    validationVersion: config.versions.validationVersion,
    trustVersion: config.versions.trustVersion,
    platformVersion: config.versions.platformVersion,
    reportVersion: config.versions.reportVersion,
    environment: config.environment,
    watermark: config.watermark,
    reportId: report.reportId,
    reportType: String(report.reportType),
  };
}

/** Build professional institutional sections from existing report models. */
export function buildExportDocument(
  report: InstitutionalReport,
  config: ExportConfiguration,
  options?: { generatedBy?: string }
): ExportDocument {
  const metadata = buildExportMetadata(report, config, options?.generatedBy);
  const s = report.summary;
  const v = report.validationMetrics;
  const t = report.trustMetrics;

  const sections: ExportDocumentSection[] = [
    {
      id: "cover",
      heading: "Cover Page",
      paragraphs: [
        report.title,
        `Report Type: ${report.reportType}`,
        `Report ID: ${report.reportId}`,
        `Generated On: ${metadata.generatedOn}`,
        `Generated By: ${metadata.generatedBy}`,
        `Environment: ${metadata.environment}`,
        metadata.watermark,
      ],
    },
    {
      id: "executive_summary",
      heading: "Executive Summary",
      paragraphs: [
        `Overall Validation Score: ${s.overallValidationScore}`,
        `Integrity Score: ${s.integrityScore}`,
        `Trust Score: ${s.trustScore}`,
        `Overall Health: ${s.overallHealth}`,
        `Recommendation Quality: ${s.recommendationQuality}`,
        `Trade Quality: ${s.tradeQuality}`,
        ...(report.recommendations.slice(0, 5).map((r) => `• ${r}`)),
      ],
    },
    {
      id: "market_summary",
      heading: "Market Summary",
      paragraphs: [
        `Reporting Period: ${report.reportingPeriod.from} → ${report.reportingPeriod.to}`,
        `Detail Level: ${report.detailLevel}`,
        `Partial Report: ${report.partial ? "Yes" : "No"}`,
        `Filters: stock=${report.filters.stock ?? "all"}; sector=${report.filters.sector ?? "all"}; exchange=${report.filters.exchange ?? "all"}`,
      ],
    },
    {
      id: "validation_summary",
      heading: "Validation Summary",
      paragraphs: [
        `Total Validations: ${v.totalValidations}`,
        `Passed: ${v.passed}`,
        `Failed: ${v.failed}`,
        `Warnings: ${v.warnings}`,
        `Critical: ${v.critical}`,
        `Average Runtime (ms): ${v.averageRuntime}`,
      ],
      tables: [
        {
          headers: ["Module", "Status", "Score", "Success %", "Trend"],
          rows: report.moduleScores.map((m) => [
            m.module,
            m.status,
            String(m.averageScore),
            String(m.successPercent),
            m.trend,
          ]),
        },
      ],
    },
    {
      id: "trust_summary",
      heading: "Trust Summary",
      paragraphs: [
        `Average Trust Score: ${t.averageTrustScore}`,
        `Rejected Objects: ${t.rejectedObjects}`,
        `Hallucination Score: ${s.hallucinationScore}`,
        `Historical Score: ${s.historicalScore}`,
      ],
      tables: [
        {
          headers: ["Classification", "Count"],
          rows: Object.entries(t.trustDistribution).map(([k, val]) => [
            k,
            String(val),
          ]),
        },
      ],
    },
    {
      id: "ai_explainability",
      heading: "AI Explainability",
      paragraphs: [
        `AI Version: ${metadata.aiVersion}`,
        `Analytics Health Score: ${report.analyticsSummary.healthScore}`,
        `Prediction Confidence: ${String(
          (report.analyticsSummary.predictionAnalytics as { averageConfidence?: number })
            ?.averageConfidence ?? "n/a"
        )}`,
        `Advisory Only: ${String(
          (report.analyticsSummary.predictionAnalytics as { advisoryOnly?: boolean })
            ?.advisoryOnly ?? true
        )}`,
        ...report.recommendations.slice(0, 10).map((r) => `Insight: ${r}`),
      ],
    },
    {
      id: "opportunity_list",
      heading: "Opportunity List",
      paragraphs:
        report.recommendations.length > 0
          ? report.recommendations.map((r, i) => `${i + 1}. ${r}`)
          : ["No opportunity recommendations in this report model."],
    },
    {
      id: "tomorrow_watchlist",
      heading: "Tomorrow Watchlist",
      paragraphs: [
        report.reportType === "TomorrowWatchlistReport" ||
        report.reportType === "RecommendationReport"
          ? "Watchlist derived from recommendation / opportunity validation models."
          : "Watchlist section populated when exporting Tomorrow Watchlist Report.",
        ...report.moduleScores
          .filter((m) =>
            /recommend|opportunity|watchlist/i.test(m.module)
          )
          .slice(0, 10)
          .map(
            (m) =>
              `${m.module}: score ${m.averageScore}, success ${m.successPercent}%, trend ${m.trend}`
          ),
      ],
    },
    {
      id: "historical_validation",
      heading: "Historical Validation",
      paragraphs: [
        `Historical Score: ${s.historicalScore}`,
        `Trend Analysis: ${JSON.stringify(report.analyticsSummary.trendAnalysis)}`,
        `Failure Analytics: ${JSON.stringify(report.analyticsSummary.failureAnalytics)}`,
      ],
      chartRefs: [
        {
          id: "hist-trend",
          title: "Historical Validation Trend",
          description: "Reuses analytics trendAnalysis model from Reporting Engine.",
        },
      ],
    },
    {
      id: "risk_analysis",
      heading: "Risk Analysis",
      paragraphs: [
        ...report.warnings.slice(0, 15).map((w) => `Warning: ${w}`),
        ...report.errors.slice(0, 15).map((e) => `Error: ${e}`),
        report.warnings.length === 0 && report.errors.length === 0
          ? "No material warnings or errors recorded."
          : "",
      ].filter(Boolean),
    },
    {
      id: "charts",
      heading: "Charts",
      paragraphs: [
        "Chart models reused from Reporting Engine analytics where available.",
      ],
      chartRefs: [
        {
          id: "module-scores",
          title: "Module Score Distribution",
          description: `${report.moduleScores.length} modules from report.moduleScores`,
        },
        {
          id: "trust-distribution",
          title: "Trust Distribution",
          description: "From report.trustMetrics.trustDistribution",
        },
        {
          id: "health-score",
          title: "Analytics Health Score",
          description: `healthScore=${report.analyticsSummary.healthScore}`,
        },
      ],
    },
    {
      id: "appendix",
      heading: "Appendix",
      paragraphs: [
        `Engine Version: ${report.engineVersion}`,
        `Configuration Version: ${report.auditInformation.configurationVersion}`,
        `Audit Generated By: ${report.auditInformation.generatedBy}`,
        `Source Modules: ${report.auditInformation.sourceModules.join(", ") || "n/a"}`,
        `Sections Included: ${report.sectionsIncluded.join(", ")}`,
        `AI Version: ${metadata.aiVersion}`,
        `Validation Version: ${metadata.validationVersion}`,
        `Trust Version: ${metadata.trustVersion}`,
        `Platform Version: ${metadata.platformVersion}`,
        `Report Version: ${metadata.reportVersion}`,
        `Export Engine: ${config.versions.exportEngineVersion}`,
        `Watermark: ${metadata.watermark}`,
      ],
    },
    {
      id: "disclaimer",
      heading: "Disclaimer",
      paragraphs: [config.disclaimer],
    },
  ];

  return {
    title: report.title,
    subtitle: `${report.reportType} · ${metadata.generatedOn}`,
    metadata,
    sections,
    disclaimer: config.disclaimer,
  };
}
