/**
 * Professional PDF exporter — pure TypeScript PDF generation (no external deps).
 */

import type { InstitutionalReport } from "../ReportBuilder";
import type { ExportConfiguration } from "./ExportConfiguration";
import {
  buildExportDocument,
  type ExportDocument,
  type ExportReportMetadata,
} from "./ExportDocument";

export interface PdfExportResult {
  format: "PDF";
  mimeType: "application/pdf";
  filename: string;
  bytes: Uint8Array;
  base64: string;
  metadata: ExportReportMetadata;
  pageCount: number;
  document: ExportDocument;
}

export class PDFExporter {
  constructor(private readonly config: ExportConfiguration) {}

  export(
    report: InstitutionalReport,
    options?: { generatedBy?: string }
  ): PdfExportResult {
    const document = buildExportDocument(report, this.config, options);
    const lines = flattenDocumentLines(document);
    const { bytes, pageCount } = assemblePdf(lines, document.metadata.watermark);
    const filename = sanitizeFilename(
      `${report.reportType}-${report.reportId}.pdf`
    );
    return {
      format: "PDF",
      mimeType: "application/pdf",
      filename,
      bytes,
      base64: uint8ToBase64(bytes),
      metadata: document.metadata,
      pageCount,
      document,
    };
  }
}

function flattenDocumentLines(doc: ExportDocument): string[] {
  const lines: string[] = [
    doc.title,
    doc.subtitle,
    `Watermark: ${doc.metadata.watermark}`,
    `Generated On: ${doc.metadata.generatedOn}`,
    `Generated By: ${doc.metadata.generatedBy}`,
    `AI Version: ${doc.metadata.aiVersion}`,
    `Validation Version: ${doc.metadata.validationVersion}`,
    `Trust Version: ${doc.metadata.trustVersion}`,
    `Platform Version: ${doc.metadata.platformVersion}`,
    `Report Version: ${doc.metadata.reportVersion}`,
    `Environment: ${doc.metadata.environment}`,
    "",
  ];
  for (const section of doc.sections) {
    lines.push(`## ${section.heading}`);
    for (const p of section.paragraphs) {
      lines.push(p);
    }
    if (section.tables) {
      for (const table of section.tables) {
        lines.push(table.headers.join(" | "));
        for (const row of table.rows.slice(0, 40)) {
          lines.push(row.join(" | "));
        }
      }
    }
    if (section.chartRefs) {
      for (const chart of section.chartRefs) {
        lines.push(`[Chart] ${chart.title}: ${chart.description}`);
      }
    }
    lines.push("");
  }
  lines.push(doc.disclaimer);
  return lines.map((l) => asciiSafe(l));
}

function assemblePdf(
  lines: string[],
  watermark: string
): { bytes: Uint8Array; pageCount: number } {
  const linesPerPage = 48;
  const pages: string[][] = [];
  for (let i = 0; i < lines.length; i += linesPerPage) {
    pages.push(lines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push([watermark]);

  const objs: Array<{ num: number; body: string }> = [];
  let num = 1;
  const catalogNum = num++;
  const pagesNum = num++;
  const fontNum = num++;
  const pageNums: number[] = [];

  for (const pageLines of pages) {
    const streamParts = [
      "BT",
      "/F1 9 Tf",
      "50 760 Td",
      "12 TL",
      `(${pdfEscape(watermark.slice(0, 80))}) Tj`,
      "T*",
      "T*",
    ];
    for (const line of pageLines) {
      streamParts.push(`(${pdfEscape(line.slice(0, 95))}) Tj`);
      streamParts.push("T*");
    }
    streamParts.push("ET");
    const stream = streamParts.join("\n");
    const contentNum = num++;
    objs.push({
      num: contentNum,
      body: `<< /Length ${byteLength(stream)} >>\nstream\n${stream}\nendstream`,
    });
    const pageNum = num++;
    pageNums.push(pageNum);
    objs.push({
      num: pageNum,
      body: `<< /Type /Page /Parent ${pagesNum} 0 R /MediaBox [0 0 612 792] /Contents ${contentNum} 0 R /Resources << /Font << /F1 ${fontNum} 0 R >> >> >>`,
    });
  }

  const all = [
    {
      num: catalogNum,
      body: `<< /Type /Catalog /Pages ${pagesNum} 0 R >>`,
    },
    {
      num: pagesNum,
      body: `<< /Type /Pages /Kids [${pageNums
        .map((n) => `${n} 0 R`)
        .join(" ")}] /Count ${pageNums.length} >>`,
    },
    {
      num: fontNum,
      body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    },
    ...objs,
  ].sort((a, b) => a.num - b.num);

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of all) {
    offsets[obj.num] = byteLength(pdf);
    pdf += `${obj.num} 0 obj\n${obj.body}\nendobj\n`;
  }
  const xrefPos = byteLength(pdf);
  const maxObj = all[all.length - 1]?.num ?? 0;
  pdf += `xref\n0 ${maxObj + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= maxObj; i++) {
    const off = offsets[i] ?? 0;
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${maxObj + 1} /Root ${catalogNum} 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF`;

  return { bytes: new TextEncoder().encode(pdf), pageCount: pages.length };
}

function byteLength(s: string): number {
  return new TextEncoder().encode(s).length;
}

function pdfEscape(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function asciiSafe(text: string): string {
  return text.replace(/[^\x20-\x7E]/g, "?");
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_");
}

function uint8ToBase64(bytes: Uint8Array): string {
  if (typeof Buffer !== "undefined") {
    return Buffer.from(bytes).toString("base64");
  }
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  // eslint-disable-next-line no-undef
  return btoa(binary);
}
