/**
 * Print exporter — HTML suitable for browser print / window.print().
 */

import type { InstitutionalReport } from "../ReportBuilder";
import type { ExportConfiguration } from "./ExportConfiguration";
import {
  buildExportDocument,
  type ExportReportMetadata,
} from "./ExportDocument";

export interface PrintExportResult {
  format: "PRINT";
  mimeType: "text/html";
  filename: string;
  /** Print-ready HTML document. */
  html: string;
  metadata: ExportReportMetadata;
}

export class PrintExporter {
  constructor(private readonly config: ExportConfiguration) {}

  export(
    report: InstitutionalReport,
    options?: { generatedBy?: string }
  ): PrintExportResult {
    const document = buildExportDocument(report, this.config, options);
    const sectionsHtml = document.sections
      .map((section) => {
        const paragraphs = section.paragraphs
          .map((p) => `<p>${escapeHtml(p)}</p>`)
          .join("");
        const tables = (section.tables ?? [])
          .map((table) => {
            const head = `<tr>${table.headers
              .map((h) => `<th>${escapeHtml(h)}</th>`)
              .join("")}</tr>`;
            const body = table.rows
              .map(
                (row) =>
                  `<tr>${row
                    .map((c) => `<td>${escapeHtml(c)}</td>`)
                    .join("")}</tr>`
              )
              .join("");
            return `<table><thead>${head}</thead><tbody>${body}</tbody></table>`;
          })
          .join("");
        const charts = (section.chartRefs ?? [])
          .map(
            (c) =>
              `<div class="chart-ref"><strong>${escapeHtml(
                c.title
              )}</strong><span>${escapeHtml(c.description)}</span></div>`
          )
          .join("");
        return `<section id="${escapeHtml(section.id)}"><h2>${escapeHtml(
          section.heading
        )}</h2>${paragraphs}${tables}${charts}</section>`;
      })
      .join("\n");

    const meta = document.metadata;
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(document.title)}</title>
<style>
  @media print { .no-print { display: none !important; } body { font-size: 11pt; } }
  body { font-family: Georgia, "Times New Roman", serif; color: #111; margin: 24px; line-height: 1.45; }
  h1 { font-size: 22pt; margin-bottom: 4px; }
  h2 { font-size: 14pt; margin-top: 28px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .meta { font-size: 9pt; color: #444; margin-bottom: 16px; }
  .watermark { font-size: 9pt; letter-spacing: 0.04em; text-transform: uppercase; color: #666; margin-bottom: 12px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 9pt; }
  th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
  th { background: #f3f3f3; }
  .chart-ref { border-left: 3px solid #999; padding: 6px 10px; margin: 8px 0; background: #fafafa; }
  .disclaimer { margin-top: 32px; font-size: 9pt; color: #555; }
  .print-actions { margin-bottom: 16px; }
</style>
</head>
<body>
  <div class="print-actions no-print">
    <button onclick="window.print()">Print</button>
  </div>
  <div class="watermark">${escapeHtml(meta.watermark)}</div>
  <h1>${escapeHtml(document.title)}</h1>
  <p class="meta">${escapeHtml(document.subtitle)}</p>
  <p class="meta">
    Generated On: ${escapeHtml(meta.generatedOn)} ·
    Generated By: ${escapeHtml(meta.generatedBy)} ·
    AI ${escapeHtml(meta.aiVersion)} ·
    Validation ${escapeHtml(meta.validationVersion)} ·
    Trust ${escapeHtml(meta.trustVersion)} ·
    Platform ${escapeHtml(meta.platformVersion)} ·
    Report ${escapeHtml(meta.reportVersion)} ·
    Env ${escapeHtml(meta.environment)}
  </p>
  ${sectionsHtml}
  <div class="disclaimer"><strong>Disclaimer</strong><p>${escapeHtml(
    document.disclaimer
  )}</p></div>
</body>
</html>`;

    return {
      format: "PRINT",
      mimeType: "text/html",
      filename: sanitizeFilename(
        `${report.reportType}-${report.reportId}-print.html`
      ),
      html,
      metadata: meta,
    };
  }
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_");
}
