/**
 * Institutional AI Screener — public exports (Sprint 9D.R1–R7).
 * Composition layer only — no duplicated engine calculations.
 */

export {
  SCREEN_TYPES,
  SCREEN_ORIGINS,
  DEFAULT_SCREEN_WEIGHTS,
  isScreenType,
  resolveScreenType,
  resolveScreenWeights,
} from "./ScreenDefinition";
export type {
  ScreenType,
  ScreenOrigin,
  ScreenUniverseKind,
  ScreenSortOrder,
  ScreenRule,
  ScreenWeights,
  ScreenDefinition,
  ScreenDefinitionInput,
} from "./ScreenDefinition";

export {
  SCREEN_ENGINE_EMPTY,
  safeScreenText,
  safeScreenNumber,
  assertNoSentinelText,
} from "./ScreenModels";
export type {
  ScreenEmptyMessage,
  ScreenUniverseCandidate,
  ScreenEngineScores,
  ResolvedScreenScores,
  ScreenRunOptions,
} from "./ScreenModels";

export {
  emptyScreenRunResults,
  normalizeScreenMatch,
} from "./ScreenResult";
export type { ScreenMatchResult, ScreenRunResults } from "./ScreenResult";

export {
  buildScreenSnapshot,
  emptyScreenSnapshot,
} from "./ScreenSnapshot";
export type { ScreenSnapshot } from "./ScreenSnapshot";

export { ScreenMetricsTracker } from "./ScreenMetrics";
export type { ScreenOperationalMetrics } from "./ScreenMetrics";

export { ScreenCache } from "./ScreenCache";

export {
  registerBuiltinScreens,
  getScreen,
  listScreens,
  setScreenEnabled,
  isScreenEnabled,
  resetScreenRegistry,
} from "./ScreenRegistry";

export { ScreenRunner } from "./ScreenRunner";
export type { ScreenRunnerDeps } from "./ScreenRunner";

export {
  registerAIScreener,
  getAIScreener,
  resetAIScreener,
  registerScreen,
  runScreen,
  getResults,
  getMetrics,
  clearCache,
  runTechnicalScreen,
  runFundamentalScreen,
  runMultiFactorScreen,
  rankResults,
  buildExplainability,
  runEarningsScreen,
  runNewsScreen,
  runCorporateActionScreen,
  runManagementScreen,
  runEventScreen,
  buildEventExplainability,
  runPortfolioScreen,
  runWatchlistScreen,
  runOpportunityScreen,
  rankInstitutionalResults,
  generateResearchPriority,
  buildInstitutionalInsights,
  createStrategy,
  updateStrategy,
  deleteStrategy,
  cloneStrategy,
  saveTemplate,
  runStrategy,
  listStrategies,
  listTemplates,
  discoverIdeas,
  discoverThemes,
  discoverSectorRotation,
  rankIdeas,
  generateInstitutionalIdeas,
  buildDiscoveryInsights,
  saveScreen,
  loadScreen,
  listSavedScreens,
  compareScreens,
  openResearch,
  getTimeline,
  archiveScreen,
  favoriteScreen,
  pinScreen,
  getWorkspaceView,
} from "./AIScreener";
export type { AIScreenerRegistrationResult } from "./AIScreener";
export type {
  TechnicalScreenOptions,
  FundamentalScreenOptions,
  MultiFactorScreenOptions,
  IntelligenceScreenResult,
  ScreenResultCard,
  ScreenRankingMode,
  ExplainabilityInput,
  EarningsScreenOptions,
  NewsScreenOptions,
  CorporateActionScreenOptions,
  ManagementScreenOptions,
  EventCorrelationOptions,
  EventScreenResult,
  EventExplainabilityInput,
  PortfolioScreenOptions,
  WatchlistScreenOptions,
  OpportunityScreenOptions,
  InstitutionalScreenResult,
  InstitutionalResultCard,
  InstitutionalScoreFactors,
  ResearchPriorityBand,
  InsightBuildInput,
  StrategyDefinition,
  StrategyDefinitionInput,
  StrategyExecutionResult,
  StrategyRunOptions,
  DiscoveryCandidate,
  DiscoveryIdeaCard,
  DiscoveryInsight,
  DiscoveryResult,
  InstitutionalIdeaOptions,
  OpportunityDiscoveryOptions,
  SectorRotationCard,
  ThemeCard,
  SavedScreenRecord,
  ScreenComparisonResult,
  ScreenTimelineEntry,
  ResearchBridgeTarget,
  WorkspaceView,
  SaveScreenInput,
  ComparableSide,
  OpenResearchOptions,
  TimelineSnapshot,
} from "./AIScreener";

export {
  SCREEN_INTELLIGENCE_EMPTY,
  SCREEN_GRADES,
  SCREEN_RANKING_MODES,
  gradeFromScore,
  emptyScoreFactors,
  emptyExplainability,
  emptyIntelligenceResult,
  normalizeResultCard,
  ScreenScoringEngine,
  composeScreenScoreFactors,
  deriveTechnicalStrength,
  deriveFundamentalStrength,
  deriveMomentumStrength,
  scoreCandidate,
  ScreenRankingEngine,
  rankScreenResults,
  ScreenExplainabilityEngine,
  buildScreenExplainability,
  TechnicalScreenEngine,
  TECHNICAL_FILTER_IDS,
  TECHNICAL_FILTERS,
  FundamentalScreenEngine,
  FUNDAMENTAL_FILTER_IDS,
  FUNDAMENTAL_FILTERS,
  MultiFactorScreenEngine,
  SCREEN_EVENT_EMPTY,
  emptyEventScoreFactors,
  emptyEventExplainability,
  emptyEventScreenResult,
  normalizeEventResultCard,
  EventExplainabilityEngine,
  composeEventScoreFactors,
  scoreEventCandidate,
  EventRankingEngine,
  rankEventResults,
  EarningsScreenEngine,
  EARNINGS_SCREEN_IDS,
  EARNINGS_SCREEN_LABELS,
  NewsScreenEngine,
  NEWS_SCREEN_IDS,
  NEWS_SCREEN_LABELS,
  CorporateActionScreenEngine,
  CORPORATE_ACTION_SCREEN_IDS,
  CORPORATE_ACTION_SCREEN_LABELS,
  ManagementCommentaryScreenEngine,
  MANAGEMENT_SCREEN_IDS,
  MANAGEMENT_SCREEN_LABELS,
  EventCorrelationScreenEngine,
  INSTITUTIONAL_SCREEN_EMPTY,
  PORTFOLIO_SCREEN_IDS,
  PORTFOLIO_SCREEN_LABELS,
  WATCHLIST_SCREEN_IDS,
  WATCHLIST_SCREEN_LABELS,
  recommendationFromScore,
  emptyInstitutionalFactors,
  emptyInstitutionalInsight,
  emptyInstitutionalScreenResult,
  normalizeInstitutionalCard,
  InstitutionalRankingEngine,
  composeInstitutionalScoreFactors,
  scoreInstitutionalCandidate,
  classifyInstitutionalRecommendation,
  ResearchPriorityEngine,
  ScreenInsightEngine,
  PortfolioScreenEngine,
  WatchlistScreenEngine,
  OpportunityScreenEngine,
} from "./intelligence";
export type {
  ScreenIntelligenceEmptyMessage,
  ScreenGrade,
  ScreenScoreFactors,
  ScreenExplainability,
  TechnicalFilterId,
  TechnicalFilterSpec,
  FundamentalFilterId,
  FundamentalFilterSpec,
  ScreenEventEmptyMessage,
  EventScreenMode,
  ScreenEventCandidate,
  EventScoreFactors,
  EventExplainability,
  EventResultCard,
  EventRankingMode,
  EarningsScreenId,
  NewsScreenId,
  CorporateActionScreenId,
  ManagementScreenId,
  InstitutionalScreenEmptyMessage,
  InstitutionalRecommendation,
  InstitutionalScreenMode,
  PortfolioScreenId,
  WatchlistScreenId,
  InstitutionalCandidate,
  InstitutionalInsight,
} from "./intelligence";

/* ── Sprint 9D.R5 — Institutional Strategy Screener ───────────────── */

export {
  STRATEGY_RULE_CATEGORIES,
  STRATEGY_COMPARISON_OPERATORS,
  STRATEGY_LOGIC_OPERATORS,
  STRATEGY_ORIGINS,
  STRATEGY_EMPTY,
  BUILTIN_TEMPLATE_IDS,
  isLeafRule,
  isRuleGroup,
  createLeafRule,
  createRuleGroup,
  evaluateRuleNode,
  collectMatchedFailedRules,
  normalizeStrategyDefinition,
  normalizeStrategyCard,
  normalizeSavedTemplateCard,
  normalizeStrategyExplainability,
  emptyStrategyExecutionResult,
  buildStrategyFromLeaves,
  countRules,
  summarizeRules,
  validateRuleTree,
  previewStrategy,
  registerBuiltinTemplates,
  getBuiltinTemplates,
  resetStrategyLibrary,
  resetStrategyModule,
  resetBuiltinTemplateFlag,
  getStrategy,
  renameStrategy,
  setStrategyFavorite,
  getTemplate,
  deleteTemplate,
  StrategyEngine,
  toInstitutionalCandidate,
} from "./strategy";
export type {
  StrategyRuleCategory,
  StrategyComparisonOperator,
  StrategyLogicOperator,
  StrategyLeafRule,
  StrategyRuleGroup,
  StrategyRuleNode,
  StrategyOrigin,
  StrategyEmptyMessage,
  StrategyCard,
  SavedTemplateCard,
  StrategyExplainability,
  StrategyUniverseCandidate,
  BuiltinTemplateId,
} from "./strategy";

/* ── Sprint 9D.R6 — AI Discovery Engine ───────────────────────────── */

export {
  DISCOVERY_EMPTY,
  DISCOVERY_IDEA_CATEGORIES,
  DISCOVERY_KINDS,
  THEME_IDS,
  THEME_LABELS,
  THEME_MATCHERS,
  emptyDiscoveryScoreFactors,
  emptyDiscoveryIdeaCard,
  emptyThemeCard,
  emptySectorRotationCard,
  emptyDiscoveryInsight,
  emptyDiscoveryResult,
  normalizeDiscoveryScoreFactors,
  normalizeDiscoveryIdeaCard,
  normalizeThemeCard,
  normalizeSectorRotationCard,
  normalizeDiscoveryInsight,
  toInstitutionalFromDiscovery,
  composeDiscoveryScoreFactors,
  IdeaRankingEngine,
  matchThemes,
  ThemeDiscoveryEngine,
  SectorRotationDiscoveryEngine,
  InstitutionalIdeaEngine,
  classifyDiscoveryKinds,
  OpportunityDiscoveryEngine,
  toDiscoveryCandidate,
  mapToDiscoveryCandidates,
  DiscoveryEngine,
} from "./discovery";
export type {
  DiscoveryEmptyMessage,
  DiscoveryIdeaCategory,
  DiscoveryKind,
  ThemeId,
  DiscoveryScoreFactors,
  DiscoveryUniverseCandidate,
} from "./discovery";

/* ── Sprint 9D.R7 — Institutional Screener Workspace ─────────────── */

export {
  WORKSPACE_EMPTY,
  QUICK_ACTIONS,
  SCORE_DELTAS,
  emptyInstitutionalScoresSummary,
  normalizeInstitutionalScoresSummary,
  emptySavedScreenRecord,
  normalizeSavedScreenRecord,
  emptyScreenHistoryRun,
  normalizeScreenHistoryRun,
  emptyComparisonTickerDelta,
  normalizeComparisonTickerDelta,
  emptyScreenComparisonResult,
  normalizeScreenComparisonResult,
  emptyScreenTimelineEntry,
  normalizeScreenTimelineEntry,
  emptyResearchBridgeTarget,
  normalizeResearchBridgeTarget,
  emptyWorkspaceCard,
  normalizeWorkspaceCard,
  emptyWorkspaceActivity,
  normalizeWorkspaceActivity,
  emptyWorkspaceView,
  normalizeScoreDelta,
  recordRun,
  listHistory,
  getRun,
  reloadRun,
  duplicateRun,
  archiveRun,
  deleteRun,
  resetHistory,
  ScreenHistoryEngine,
  compareRuns,
  compareStrategies,
  compareSectorSnapshots,
  portfolioVsMarket,
  watchlistVsMarket,
  ScreenComparisonEngine,
  listResearchBridgeIntents,
  ResearchBridgeEngine,
  TIMELINE_METRICS,
  ScreenTimelineEngine,
  saveScreen as saveScreenCore,
  loadScreen as loadScreenCore,
  listSavedScreens as listSavedScreensCore,
  deleteSavedScreen,
  pinSavedScreen,
  favoriteSavedScreen,
  archiveSavedScreen,
  listRecentSavedScreens,
  listPinnedSavedScreens,
  listFavoriteSavedScreens,
  resetSavedScreens,
  SavedScreenEngine,
  ScreenWorkspace,
  getScreenWorkspace,
  resetScreenWorkspace,
} from "./workspace";
export type {
  WorkspaceEmptyMessage,
  QuickAction,
  ScoreDelta,
  WorkspaceScreenOrigin,
  InstitutionalScoresSummary,
  ScreenHistoryRun,
  ComparisonTickerDelta,
  ResearchBridgeIntent,
  WorkspaceCard,
  WorkspaceActivity,
  TimelineMetric,
  RecordRunInput,
} from "./workspace";
