/**
 * Report templates — maps report types to included sections and titles.
 */

import type {
  ReportDetailLevel,
  ReportSectionId,
  ReportType,
  ReportingConfiguration,
} from "./ReportConfiguration";

export interface ReportTemplate {
  type: ReportType;
  title: string;
  description: string;
  sections: ReportSectionId[];
  detailLevel: ReportDetailLevel;
}

export class ReportTemplates {
  constructor(private readonly config: ReportingConfiguration) {}

  getTemplate(
    type: ReportType,
    detailLevel?: ReportDetailLevel
  ): ReportTemplate {
    const sections =
      this.config.templateSections[type] ??
      this.config.defaultSections;
    return {
      type,
      title: titleFor(type),
      description: `Institutional ${type} generated by EquityOS Reporting Engine`,
      sections: [...sections],
      detailLevel: detailLevel ?? this.config.defaultDetailLevel,
    };
  }

  listTemplates(): ReportTemplate[] {
    return Object.keys(this.config.templateSections).map((type) =>
      this.getTemplate(type)
    );
  }

  registerTemplate(
    type: ReportType,
    sections: ReportSectionId[],
    options?: { force?: boolean }
  ): { registered: boolean; skipped: boolean } {
    if (this.config.templateSections[type] && !options?.force) {
      return { registered: false, skipped: true };
    }
    this.config.templateSections[type] = [...sections];
    return { registered: true, skipped: false };
  }
}

function titleFor(type: ReportType): string {
  switch (type) {
    case "ValidationReport":
      return "Institutional Validation Report";
    case "TrustReport":
      return "Institutional Trust Report";
    case "IntegrityReport":
      return "Data Integrity Report";
    case "RecommendationReport":
      return "Recommendation Validation Report";
    case "TradeValidationReport":
      return "Trade Validation Report";
    case "HistoricalPerformanceReport":
      return "Historical Performance Report";
    case "HallucinationReport":
      return "AI Hallucination Report";
    case "AnalyticsReport":
      return "Validation Analytics Report";
    case "DashboardReport":
      return "Validation Dashboard Report";
    case "AuditReport":
      return "Validation Audit Report";
    default:
      return `Custom Report (${type})`;
  }
}
